### ISSUE TITLE
npm start doesn't run

### ISSUE THREAD

**Issue by lorddickfist** [flavioislima/HeroicGamesLauncher#1]
When I run npm start in the folder after running npm install I get this

`sh: line 1: nf: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! heroic@0.2.0-beta start: `nf start -p 3000 && electron-start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the heroic@0.2.0-beta start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ldf/.npm/_logs/2020-12-30T22_20_33_520Z-debug.log`

[Here is that log](http://ix.io/2Km0)

**Comment by CoffeeBoi47** [comment]
Im getting this issue also. It said `nf: command not found` so I did `npm install nf` and it installed it and then I ran `npm start` and I got a different error containing `Error: invalid argument start`

[Here is that error](https://pastebin.com/V72fL71a)

**Comment by lorddickfist** [comment]
> Im getting this issue also. It said `nf: command not found` so I did `npm install nf` and it installed it and then I ran `npm start` and I got a different error containing `Error: invalid argument start`
> 
> [Here is that error](https://pastebin.com/V72fL71a)

Really? I still get command not found when I run npm install nf...

**Comment by CoffeeBoi47** [comment]
the warnings for fsevents are expected because fsevents is a package for running it in MacOS which you are not so it says unsupported platform because you are not on MacOS. That is also why is says OPTIONAL DEPENDENCY

**Comment by lorddickfist** [comment]
> the warnings for fsevents are expected because fsevents is a package for running it in MacOS which you are not so it says unsupported platform because you are not on MacOS. That is also why is says OPTIONAL DEPENDENCY
 
Ah I see not used to npm :p

**Comment by lorddickfist** [comment]
> Im getting this issue also. It said `nf: command not found` so I did `npm install nf` and it installed it and then I ran `npm start` and I got a different error containing `Error: invalid argument start`
> 
> [Here is that error](https://pastebin.com/V72fL71a)

I tried to just go straight to run dist and it doesnt give an error but it does however if I launch the appimage itll launch but itll be completely white

**Comment by CoffeeBoi47** [comment]
>      I tried to just go straight to run dist and it doesnt give an error but it does however if I launch the appimage itll launch but itll be completely white

Yea that doesnt work properly either, I have an issue posted on that also. Really disappointing imo

**Comment by lorddickfist** [comment]
> > ```
> >  I tried to just go straight to run dist and it doesnt give an error but it does however if I launch the appimage itll launch but itll be completely white
> > ```
> 
> Yea that doesnt work properly either, I have an issue posted on that also. Really disappointing imo

It is beta so no big deal eventually itll get aur etc. I checked releases and it has an app image only I tried that logged in via xterm it logged but crashes upon updating game list

**Comment by CoffeeBoi47** [comment]
> It is beta so no big deal
Yea I know but im saying it kinda sucks that it just came out and almost none of the options to make/run it work. I really hope the npm thing gets fixed soon so I can contribute to this, cant make changes currently because well theres no way to run the app after I make em lol. The pre-built AppImage works for me on Ubuntu 20.04 btw

**Comment by lorddickfist** [comment]
> > It is beta so no big deal
> 
> Yea I know but im saying it kinda sucks that it just came out and almost none of the options to make/run it work. I really hope the npm thing gets fixed soon so I can contribute to this, cant make changes currently because well theres no way to run the app after I make em lol. The pre-built AppImage works for me on Ubuntu 20.04 btw

Would you mind posting the output of it via curl so I can compare?

**Comment by CoffeeBoi47** [comment]
> Would you mind posting the output of it via curl so I can compare?

I have no idea what curl is or how to use it

**Comment by lorddickfist** [comment]
> > Would you mind posting the output of it via curl so I can compare?
> 
> I have no idea what curl is or how to use it

When I'm back on pc I'll give you a command to run

**Comment by flavioislima** [comment]
Hey guys! Thanks for testing and finding bugs!
I think this is just a lack of information on the README page, I'll improve that.

To be able to run `nf` you need to install `foreman` globally first.
So try to put `npm i -g foreman` on your terminal. 

Also, I'll release a debug version to run with the console opened or at least add the option to open dev tools on it.

So just to clarify, if you want just to use the app: 

- Download the AppImage
- Install legendary
- install xterm
- chmod +x heroic-0.2.0-beta.AppImage
- ./heroic-0.2.0-beta.AppImage

that should do it.

If you never run legendary before, it will ask you to login, it will open the epic games store, you need to login there and get the SID code. With the SID code, post it on the xterm that opened and the game will download your game list. Sometimes it does not reload the app automatically and I'm investigating why. If not, just close the app and run it again.

If you think is easier, before launch the app run `legendary auth` on terminal and then `legendary list-games`.

**Comment by lorddickfist** [comment]
> Hey guys! Thanks for testing and finding bugs!
> I think this is just a lack of information on the README page, I'll improve that.
> 
> To be able to run `nf` you need to install `foreman` globally first.
> So try to put `npm i -g foreman` on your terminal.
> 
> Also, I'll release a debug version to run with the console opened or at least add the option to open dev tools on it.
> 
> So just to clarify, if you want just to use the app:
> 
> * Download the AppImage
> * Install legendary
> * install xterm
> * chmod +x heroic-0.2.0-beta.AppImage
> * ./heroic-0.2.0-beta.AppImage
> 
> that should do it.
> 
> If you never run legendary before, it will ask you to login, it will open the epic games store, you need to login there and get the SID code. With the SID code, post it on the xterm that opened and the game will download your game list. Sometimes it does not reload the app automatically and I'm investigating why. If not, just close the app and run it again.
> 
> If you think is easier, before launch the app run `legendary auth` on terminal and then `legendary list-games`.
> 
> update: I just updated the README with better instructions on how to run locally and build the app. Tested cloning the repo again and it works.

Yeah install foreman manually running from npm start still [doesn't work](http://ix.io/2KrP). 
Appimage still crashes even after syncing manually with legendary

**Comment by flavioislima** [comment]
> Yeah install foreman manually running from npm start still [doesn't work](http://ix.io/2KrP).
> Appimage still crashes even after syncing manually with legendary
> EDIT: all 3 aur do not work either for me

That's weird. I just installed the same node version as you, 15.5.0. Did an `npm i -g foreman` and `npm install` and `npm start` and it worked perfectly.

How did you install your nodejs? using the package distribution or a tool like NVM and ASDF?
I personally had issues installing node using the official package because global packages need to be installed as root and when executing, some of them needs `sudo`.

So, today I use ASDF but NVM is also fine and easier to use. And the node stays in your home folder, all global packages stay there.

Give it a try.

**Comment by octoshrimpy** [comment]
the AUR/bin works for me, and I was able to get the dev repo to compile and livereload on filechange without problems. I followed the newly updated readme (yesterday) and everything is working on my end. on linux, at least for me, `npm -g` won't install anything correctly without sudo.

**Comment by flavioislima** [comment]
> the AUR/bin works for me, and I was able to get the dev repo to compile and livereload on filechange without problems. I followed the newly updated readme (yesterday) and everything is working on my end. on linux, at least for me, `npm -g` won't install anything correctly without sudo.

That's one of the biggest issues with Node, if you're not a regular dev is hard to know that installing it as a global package is one of the worst ideas because using Sudo to install npm packages is a big security issue.

If I were you, I would remove it and then install NVM and install node from there. It works a lot better, and you will not need sudo for anything. 😃

**Comment by flavioislima** [comment]
@lorddickfist is this still an issue? can we close it?

**Comment by lorddickfist** [comment]
> @lorddickfist is this still an issue? can we close it?

I honestly hadn't tried since last post. If you want you can close it since I'm preoccupied with work

**Comment by flavioislima** [comment]
> > @lorddickfist is this still an issue? can we close it?
> 
> I honestly hadn't tried since last post. If you want you can close it since I'm preoccupied with work

Ok, I'll close it. Try the new info on the README and if it doesn't work you can reach me.
