### ISSUE TITLE
Issue syncing library items

### ISSUE THREAD

**Issue by GregTheHun** [flavioislima/HeroicGamesLauncher#101]
Well, I just bought a game on the Epic store, but it appears to not show up on my list of game even after:

- Relaunching
- Logging out and back in with SID
- Refreshing library

I'd love to play this new game too.

**Comment by flavioislima** [comment]
Which game is that?

**Comment by flavioislima** [comment]
If it is Battlefront 2 it doesn't work as discussed here: #48

**Comment by GregTheHun** [comment]
Actually, it's apparently the Star Wars Triple bundle, which includes Battlefront II.

So, I guess I'll have to read up on the issue and try and resolve, if possible.

**Comment by flavioislima** [comment]
All Origin games needs Origin to install them, is not epic, even if you go to windows or use the lutris versino, you will need origin to download, that's why Heroic do not get any info, because we can only show games that are downloadable through epics.

**Comment by GregTheHun** [comment]
Maybe this issue can be pinned and closed.

The #48 link you sent above was helpful.
