### ISSUE TITLE
Remember filter on startup

### ISSUE THREAD

**Issue by alexheretic** [flavioislima/HeroicGamesLauncher#103]
When I startup the launcher the game filter is set to ***All*** and I'm always staring at `>OBSERVER_`.

I'd like it to be whatever it was from the last session, e.g. ***Installed***. This is also related to why I wanted #75.

**Comment by flavioislima** [comment]
@alexheretic added on latest release. So now it will 'store' the latest filter when exit.

**Comment by alexheretic** [comment]
Thanks! Unfortunately this doesn't work for me. After quitting then restarting the app the localStorage is empty. I had a quick look and setting the browser `webPreferences.partition` fixes this. PR: #108

**Comment by flavioislima** [comment]
Weird but this worked for me using the appImage. What package have you installed?

**Comment by alexheretic** [comment]
aur `heroic-games-launcher-bin`

**Comment by alexheretic** [comment]
I could also reproduce just using `npm start`.

**Comment by flavioislima** [comment]
Weird. I'm also using the AUR version and it is working as on this video:
Check if you're using the 1.20.0-2 of the bin one.
https://user-images.githubusercontent.com/26871415/105643691-92bc1280-5e91-11eb-8b51-9ae947d2f464.mp4

**Comment by alexheretic** [comment]
I think I see an issue. I'm closing the window, rather than selecting "Quit". This isn't actually shutting down the launcher. (Gnome doesn't support tray icons so persistent running doesn't really work well). 

When I start up the new launcher it'll be running 2 of them and not picking up the localStorage. If I use "Quit" it seems to work as is.

Can we get the window-close to be identical to quit, or at least have an option for that?

**Comment by flavioislima** [comment]
@alexheretic implemented the options on latest release!
Also now heroic will have only one instance at the time. 
Thanks

**Comment by alexheretic** [comment]
Perfect, thank you! I'll check it out when I get when I get a sec.

**Comment by alexheretic** [comment]
Yep all working well, nice one!
