### ISSUE TITLE
Improve "Games Downloading" exit prompt

### ISSUE THREAD

**Issue by alexheretic** [flavioislima/HeroicGamesLauncher#104]
When exiting the launcher there's an exit prompt.

![exit-promt](https://user-images.githubusercontent.com/2331607/105631571-01c04980-5e47-11eb-97d7-e7414b71cdff.png)

This always shows, even if no game is actually downloading. This confused me a bit when I first used the launcher.

It would be cool to have:
* Different text when no games are downloading.
* Option to disable the confirmation totally when nothing is downloading.

Or more simply:
* Don't show any confirmation prompt when no games are downloading.

**Comment by flavioislima** [comment]
Im removing this prompt on next version now that heroic will have a tray icon. So it will hide and if the user wants to quit, just quit. The games will start from where they were stopped in case a download gets interrupted. And there is also now a notification when a game finishes downloading.
