### ISSUE TITLE
Minor UI Bug: "Settings" Header only highlighted in General Tab.

### ISSUE THREAD

**Issue by camr0** [flavioislima/HeroicGamesLauncher#110]
Found a very minor UI bug. The "Settings" header is only highlighted(turns orange) on the "General" tab. When the "Wine" or "Other" settings tab is selected, the "Settings" header is no longer highlighted.

**Comment by flavioislima** [comment]
Yeah this is an old bug that I was lazy to fix before but I thin now is the time :D

**Comment by flavioislima** [comment]
Fixed on latest release
