### ISSUE TITLE
Can't delete, uninstall or modify a game from library when you import a game path

### ISSUE THREAD

**Issue by tr1p0p** [flavioislima/HeroicGamesLauncher#118]
Hi, so i wanna talk about a issues i have here :

I try to import a game, already install in my other DD, and i make a mistake. How can i undo or cancel that ?

So, for more context : try to put Civ VI path, and accidentally put the root folder path (with DLC folders and stuffs) and NOT the folder with the game executable. So now, i can't uninstall, can't launch it AND can't modify anything, just stuck.

Maybe they're are config files somewhere or a library files when i can manually delete this game path, but for now i have no fix for this.

Did you think about a way to modify the path when something like that ?

Thks for the amazing work on this app !

**Comment by flavioislima** [comment]
the thing is that Heroic does not get an error if you choose a folder that does not contain the game. 
to fix this, for now, remove the install information of the game from `.config/legendary/installed.json` and import again.
I'll add an option to move the game in the future that could be used to fix this kind of thing as well.

**Comment by flavioislima** [comment]
Option to move games added on latest release
