### ISSUE TITLE
multiple, Advanced Options

### ISSUE THREAD

**Issue by jarrard** [flavioislima/HeroicGamesLauncher#119]
Just wondering if the app allows you to put multiple advanced options for the pre-launch environment?  I tried putting two things in separated by a space but it appeared to not take affect? one of those was wineoverrides which uses "", maybe that's an illegal character?

**Comment by jarrard** [comment]
Noticed the last setting don't take affect unless you have a space after them. So I had RADV_DEBUG=llvm but it had to be RADV_DEBUG=llvm(space)

**Comment by jarrard** [comment]
I was trying to do the following but it seemed only the last one took affect or something. 

RADV_DEBUG=llvm PROTON_NO_ESYNC=1 WINEDLLOVERRIDES=winedbg.exe=d

**Comment by flavioislima** [comment]
Noticed this 'space' issues yesterday when was playing as well. I'll fix on next release.
But about the options, I tried using 5 different options and all worked.
There is no issue using `'` or `"` or even `,`

**Comment by jarrard** [comment]
ok, well I'll try using , in the future and hope for the best.

**Comment by jarrard** [comment]
This might be related to #120 but I forgot to mention it. I found GTA5 for example would not run if the have a SPACE after any advanced commands such as RADV_DEBUG=llvm.. without a space at the end the game would refuse to run. 

I believe this might be because the command is setup without correct syntax so perhaps its doing RADV_DEBUG=llvmgame.exe and adding a space corrects the command line.

You may have already fixed this, I do not know. But having some smart syntax translation can prevent some of this?¿

**Comment by flavioislima** [comment]
> This might be related to #120 but I forgot to mention it. I found GTA5 for example would not run if I didn't have a SPACE after any advanced commands, such as RADV_DEBUG=llvm.. without a space at the end the game would refuse to run.
> 
> I believe this might be because the command is setup without correct syntax so perhaps its doing RADV_DEBUG=llvmgame.exe and adding a space corrects the command line.
> 
> You may have already fixed this, I do not know. But having some smart syntax translation can prevent some of this?¿

It is already fixed on the main branch. Could be the case if you were using game mode since it is the first command after the options. But I'll release a new version this weekend with this bug fix among others.

**Comment by flavioislima** [comment]
Fixed on latest release
