### ISSUE TITLE
JavaScript-Error at startup

### ISSUE THREAD

**Issue by raphipod** [flavioislima/HeroicGamesLauncher#125]
**Describe the bug**
At every startup a JavaScript error pops up with the following message:

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from null
at IpcMainImpl.<anonymous> (/opt/heroic/resources/app.asar/-build/main.js:188:37)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
at Object.emit (events.js:315:20)

**To Reproduce**
1. Open the app

**Expected behavior**
App should open without errors, but doesn't.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS (Ubuntu) using stock GNOME & popos-shell
 - Version: 1.2.2 Absalom (Linux)
 -> Shouldn't be a Wine related error, but if necessary: wine 5.0-3ubuntu1(Pop!_OS stock wine)

**Additional context**

After getting this error, pressing OK returns to the App as if nothing happened and continuing as normal without other errors.

**Comment by flavioislima** [comment]
I could not reproduce it but looking at the error I think I know what is causing and I'll release a fix.

**Comment by flavioislima** [comment]
@raphipod can you try on version 1.3.0 to check if it was fixed?

**Comment by DuttaAB-dev** [comment]
I was facing the same issue and yes, it has been completely fixed in the latest release.

**Comment by raphipod** [comment]
Hmm, I updated the Debian package from 1.2.2 to 1.3.0 as you said, and it only shows "Loading" at startup. Weird. 

I'm removing Heroic and install it again and I'll inform you if that's happened.

**Comment by flavioislima** [comment]
@raphipod I got the issue, is related with #127 . I'm releasing a hot fix in a few minutes

**Comment by raphipod** [comment]
Ah ok. Thanks for your patience.

Closing this now.
