### ISSUE TITLE
HGL Will infinitely stay on the "Loading" animation with a javascript error in terminal.

### ISSUE THREAD

**Issue by Kirottu** [flavioislima/HeroicGamesLauncher#127]
**Describe the bug**
When starting HGL, it will infinitely show the "Loading" animation, with a javascript error if ran from the terminal
```
Error occurred in handler for 'readFile': TypeError: Cannot read property 'value' of undefined
    at /opt/heroic/resources/app.asar/build/main.js:414:44
    at Array.map (<anonymous>)
    at /opt/heroic/resources/app.asar/build/main.js:383:18
    at Generator.next (<anonymous>)
    at fulfilled (/opt/heroic/resources/app.asar/build/main.js:24:58)
```

**To Reproduce**
1. Run HGL

**Expected behavior**
I would expect HGL to launch normally

**Screenshots**
![image](https://user-images.githubusercontent.com/56396750/106365179-7d852f00-633c-11eb-8f40-246b1b37ce49.png)

**Desktop (please complete the following information):**
 - OS: Arch
 - Version: Just updated system
-  Game: No game involved
-  Wine/Proton version: No wine/proton involved

**Comment by flavioislima** [comment]
Is this on 1.3.0?

**Comment by flavioislima** [comment]
I found the issue, I'm releasing a hotfix. 
It seems that you have some game/DLC that does not have a 'FolderName' on the manifest.

**Comment by raphipod** [comment]
Yep, it works now!

**Comment by flavioislima** [comment]
@raphipod thanks for the quick check! :D

**Comment by Kirottu** [comment]
Alright seems like this is fixed now, thanks for the quick fix!
