### ISSUE TITLE
Cant install games into directory with spaces in it

### ISSUE THREAD

**Issue by CoffeeBoi47** [flavioislima/HeroicGamesLauncher#13]
I tried to install a game to my second drive with spaces in the name, legandary then sees that /media/coffee/Not doesnt exist and attemps to create it and fails to do so.

![Screenshot from 2021-01-03 09-17-41](https://user-images.githubusercontent.com/61567332/103483455-8ff36380-4da4-11eb-8fd2-f18c13709231.png)

**Comment by flavioislima** [comment]
NIce catch!  I'll look into that.

**Comment by flavioislima** [comment]
Fixed on the new version: https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/0.4.1-beta
