### ISSUE TITLE
Some games are missing

### ISSUE THREAD

**Issue by jediafr** [flavioislima/HeroicGamesLauncher#131]
Star Wars Battlefront; Pathway,Next Up Hero   are missing in the available games (they are available on my epic page though). 
 Even after a library refresh the game are missing.

**Comment by flavioislima** [comment]
For battlefront check #48. The others I don't know, can you try installing legendary and do a legendary list-games? I don't have those on my library. Do you know if they use another launcher like origin to run? Because some games that do not launch directly through epic would not be shown on heroic and legendary as well.

**Comment by jediafr** [comment]
i ll investigate but thank you for your quick reply !

**Comment by flavioislima** [comment]
@jediafr Can you try the new release?

I just realize I have Pathway and Next up Hero and they are appearing on my library:
![image](https://user-images.githubusercontent.com/26871415/107160576-717e1a80-6997-11eb-8329-f4dc576be2d7.png)
![image](https://user-images.githubusercontent.com/26871415/107160584-79d65580-6997-11eb-93a7-648d3af30823.png)

**Comment by jediafr** [comment]
Hi Flavio, Pathway and Next up hero are now apprearing, which leaves
only Star wars missing but it is no big deal (i couldnt test the cli
yet sorry for that).

On 2/7/21, Flavio F Lima <notifications@github.com> wrote:
> @jediafr Can you try the new release?
>
> I just realize I have Pathway and Next up Hero and they are appearing on my
> library:
> ![image](https://user-images.githubusercontent.com/26871415/107160576-717e1a80-6997-11eb-8329-f4dc576be2d7.png)
> ![image](https://user-images.githubusercontent.com/26871415/107160584-79d65580-6997-11eb-93a7-648d3af30823.png)
>
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/flavioislima/HeroicGamesLauncher/issues/131#issuecomment-774774881


-- 
Kinds regards,

Jean-denis.
