### ISSUE TITLE
After launching a game Heroic creates wrong folder for save files

### ISSUE THREAD

**Issue by Sebastian1978** [flavioislima/HeroicGamesLauncher#132]
After launching a game Heroic creates wrong folder for save files.
For Torchlight 2 it should create folders {userdir}/My Games/runic games/torchlight 2/save/ as written in default config.
Unfortunately it creates folder with name "{userdir}" in Home folder. All other folders are ok.

See screenshots.

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [1.3.1 Doflamingo
-  Game: Torchlight 2
-  Wine/Proton version: 6.0

**Comment by Sebastian1978** [comment]
![Снимок экрана от 2021-02-02 00-33-38](https://user-images.githubusercontent.com/1432642/106521153-dbf20f00-64ee-11eb-83b1-2e8a1960ffdf.png)

**Comment by Sebastian1978** [comment]
![Снимок экрана от 2021-02-02 00-42-42](https://user-images.githubusercontent.com/1432642/106521672-a13ca680-64ef-11eb-8c9a-d7a4eaf34faf.png)

**Comment by flavioislima** [comment]
Ok. This is another edge case. I'll release a fix soon. For now, use the override to choose the correct folder.

**Comment by Sebastian1978** [comment]
@flavioislima Override option doesn't work because I downloaded save from cloud and game didn't see new config

**Comment by Sebastian1978** [comment]
It also creates wrong folders with " ' " in names. See attach
![Uploading Снимок экрана от 2021-02-02 15-42-21.png…]()

**Comment by Sebastian1978** [comment]
It also creates wrong folders with " ' " in names. See attach

**Comment by Sebastian1978** [comment]
![Uploading Снимок экрана от 2021-02-02 15-42-21.png…]()
