### ISSUE TITLE
Confusing game directories for games

### ISSUE THREAD

**Issue by Sebastian1978** [flavioislima/HeroicGamesLauncher#133]
Heroic installs games in 3 directories: Games, My Games and legendary. I think it will be better to use only one instead of 3. I suppose Games will be good because where are Lutris installed launchers.

**Comment by Linux4Good** [comment]
What do you mean install on 3 directories? 
The legendary folder will be used by legendary if you use the legendary to install and do not pass an install path argument.
If you use heroic, it won't use thar folder.
The default folder for Heroic is ~/Games/Heroic

`My games` is used for saves, this is a folder that wine maps when using AppData or something like this. You can look at the user.reg file on the prefix.

So if you do not change the default settings, heroic will always install on the default folder.
You can also choose the folder when installing.

**Comment by flavioislima** [comment]
@Sebastian1978 maybe you're confusing with the save games? I think installation is only on one directory, unless you specify that using "install on custom path" option.

**Comment by flavioislima** [comment]
@Sebastian1978 can I close this one?

**Comment by Sebastian1978** [comment]
@flavioislima yes you can. It's OK
