### ISSUE TITLE
'/home/user/~' is created when a game is started

### ISSUE THREAD

**Issue by joaquin-rossi** [flavioislima/HeroicGamesLauncher#135]
inside it there is only a '.wine' folder so probably it has to do with the wine prefix
it should use that actual user's home directory instead of creating this new one
f applicable, add screenshots to help explain your problem.

i'm using heroic-games-launcher-bin from the aur if that matters

**Comment by flavioislima** [comment]
There are a few issues with the current release with the folder creations, for both wine prefixes and save folders, when using `~/`. It is already fixed on the main branch and will be fixed on next release probably this weekend.
For now, to avoid this, just create a folder yourself or select .wine using the folder select.

**Comment by joaquin-rossi** [comment]
Great! Thank you
