### ISSUE TITLE
ram usage during install of game

### ISSUE THREAD

**Issue by barbaros83** [flavioislima/HeroicGamesLauncher#138]
**Describe the bug**

during the instalation of cities skyline, my system had 95% ram usage, and swap was over 50%
system becomes almost unresponsive

**To Reproduce**
1. install a game

**Expected behavior**
limit ram usage

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Solus
 - Version 4.2
-  Game:
-  Wine/Proton version:

**Additional context**

**Comment by flavioislima** [comment]
Hi!

This is related with the amount of workers that legendary is using to install games because now it uses the default. I'll add an option to set a lower value. It will use less ram and cpu but the download can be slower.

I'll try to add this on next version.

**Comment by DuttaAB-dev** [comment]
> Hi!
> 
> This is related with the amount of workers that legendary is using to install games because now it uses the default. I'll add an option to set a lower value. It will use less ram and cpu but the download can be slower.
> 
> I'll try to add this on next version.

Maybe make this tradeoff as an option instead? As some users might have the enough resources to experience the full speed.

**Comment by flavioislima** [comment]
Yeah, it will be an option. 👍

**Comment by flavioislima** [comment]
So the option is on the new release. Please try it :D

**Comment by barbaros83** [comment]
it works good so far, installed metro last light just now, it downloads even faster, and no system hang, also resource usage seems very good

**Comment by flavioislima** [comment]
Nice! I'll close tis issue then.
