### ISSUE TITLE
Unable to install new games

### ISSUE THREAD

**Issue by RD1K** [flavioislima/HeroicGamesLauncher#139]
When I open Heroic Games Launcher, I only see games which I've installed on my Epic Games account before. I don't have a toggle to choose between installed and not installed.

1. Open Heroic
2. The toggle isn't there

I expected to be able to search for games I haven't installed before.

![Screenshot from 2021-02-05 19-02-28](https://user-images.githubusercontent.com/48737891/107101373-14426780-67e5-11eb-9c35-85a34c296552.png)

 - OS: Manjaro
 - Version: Nibia 20.2.1
-  Game: Any, aside from Fortnite which I've installed on the account previously
-  Wine/Proton version: Proton 5.0

**Comment by flavioislima** [comment]
Hi!

Do you mean show the store games for you to buy and download? 

It is not on my plans to add the store inside Heroic. The idea is to be a launcher for the games you already own there.

**Comment by RD1K** [comment]
Yeah that's what I meant, I misunderstood. I'll try getting Epic Games Launcher in a VM to add the game then. Thanks!

**Comment by flavioislima** [comment]
You can use the website for that or try to install the Lutris version of it. :)

**Comment by RD1K** [comment]
Oh ok, thank you!
