### ISSUE TITLE
Platform filter

### ISSUE THREAD

**Issue by chernyaknikita** [flavioislima/HeroicGamesLauncher#14]
It'd be nice to have games filter to separate native Linux games and Wine/Proton games. I thougth of using ProtonDB since it has such info and even how playable game is (which is useful filter too) but idk if they have proper api and all.

**Comment by chernyaknikita** [comment]
Oh I've just realised that Epic doesn't distribute native Linux games.

**Comment by flavioislima** [comment]
Exactly. Unfortunately for now, we are stuck with Windows games.

**Comment by John-Gee** [comment]
You could filter by WineHQ or ProtonDB's ratings though.
