### ISSUE TITLE
Asks to update every time

### ISSUE THREAD

**Issue by DjSapsan** [flavioislima/HeroicGamesLauncher#143]
**Describe the bug**
I have the latest version of the game. I can successfully launch the same files in Win10. 
But in Heroic i can't launch the game. I have tried different wine's and protons etc. 
It asks for an update every time, either choice doesnt help. Full repair doesnt help also.
Other games i can run successfully.
Is there a way to launch a game without updating? Where i can look all launch arguments?

**Screenshots**
![image](https://user-images.githubusercontent.com/12209464/107153398-0243fe80-6976-11eb-8661-4e47e58e9e0f.png)

**Log:**
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] ERROR: Game is out of date, please update or launch with update check skipping!

**Desktop (please complete the following information):**
 - OS: Linux Mint 20 Cinnamon
-  Game: Satisfactory
-  Wine/Proton version: wine-6.1 (Staging), Proton-6.1-GE-1

**Comment by flavioislima** [comment]
If you say no it will be launched without update.
To check the launch arguments, just run heroic from terminal and when click play you will see the whole command.

If possible, try the same command with legendary installed to see if it will work. Heroic is just a GUI and this error is coming from Legendary.

**Comment by DjSapsan** [comment]
Interesting. Actually there was an update between switch from my Win to Linux. IDK why the update didn't work before, but i got the latest update of Heroic 40 min ago and the update is working now
