### ISSUE TITLE
KDE (Kubuntu) cant download games stabley (ping gets really high)

### ISSUE THREAD

**Issue by Games-Crack** [flavioislima/HeroicGamesLauncher#144]
**Describe the bug**
Every time i try to Download Any game my internet connection (On all devices) drops (only when using this app)
and i have to close the App and reopen it.

also a error appears every startup
![image](https://user-images.githubusercontent.com/46073213/107155837-f0b12580-697a-11eb-859f-594f76a22385.png)

**To Reproduce**
1. Go to 'An Game'
2. Click on 'Download'
3. Wait

**Expected behavior**
The Game shuld download fine without any internet loss

**Screenshots**
![image](https://user-images.githubusercontent.com/46073213/107155907-76cd6c00-697b-11eb-81f3-87f1b188a941.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version OS Ver: Linux LH-1 5.8.0-41-generic #46~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux (output of uname -a)
-  Game: (ALL)
-  Wine/Proton version: Wine 5.0 / Proton Experimental

**Additional context**

**Comment by flavioislima** [comment]
Hmm. By default, it will run one worker per CPU core that you have so it will try to use all the internet that you have. But I never got an issue about the internet going down.

On the next release, Heroic will have an option to limit the number of workers, so you will be able to test with a lower option, probably this will fix.

**Comment by flavioislima** [comment]
The other error at startup should be fixed on the next release as well.

**Comment by Games-Crack** [comment]
ok Thank You

**Comment by Games-Crack** [comment]
i'll reopen this isue if it does persist in the new release

**Comment by flavioislima** [comment]
Good.
By the way, I have a 250Mb internet (thanks Sweden), using 1 worker, games are being downloaded at 2MiB/s. With all workers enabled (12 in my case, since it is one per CPU Thread), I got all my internet being used and a lot of memory and CPU. 

I'm finishing testing the new version, might release it today or tomorrow at max.

**Comment by Games-Crack** [comment]
i only have 100mbps Thanks Germany :-D
btw i switched from windows to linux (KDE) Today. and this tool is Great All my games run!

**Comment by flavioislima** [comment]
> i only have 100mbps Thanks Germany :-D
> btw i switched from windows to linux (KDE) Today. and this tool is Great All my games run!

Nice to hear, man! :D
For me a lot run as well. The only ones that does not are the ones that uses anti cheat, but I'm most into single player games so I'm fine.

**Comment by Games-Crack** [comment]
me too (i just play multiplayers somtimes and if they dont run i will use Windows (but only then))

**Comment by Games-Crack** [comment]
do you have discord or something if you want we can talk :-)

**Comment by flavioislima** [comment]
Sure. Just drop a message there: FlavioF34rn#8389

**Comment by Games-Crack** [comment]
Games_Crack#4324 is my discord name (btw you cant send direct messages wihout an shared server so i dropped an friendship ;-) )
