### ISSUE TITLE
Heroic 1.4.0 Torchlight 2 doesn't use cloud save

### ISSUE THREAD

**Issue by Sebastian1978** [flavioislima/HeroicGamesLauncher#147]
When I load save from cloud Torchlight 2 doesn't use it

Desktop
 - OS: [Ubuntu 20.10]
 - Version []
-  Game: Torchlight 2
-  Wine/Proton version: 6.0

**Comment by flavioislima** [comment]
Torchlight is one of the games that won't work with cloud saves automatically. You will need to point to the save folder manually.
