### ISSUE TITLE
Rocket League installation stucks

### ISSUE THREAD

**Issue by realsontaran** [flavioislima/HeroicGamesLauncher#148]
Rocket league downloading stuck every time i try. I tried 3 times to install but every time it stops at some point. I installed another game without problem. There is more than enough space in the disk for game. Start heroic from terminal to detect problem. As you can see in first image, after DLManager part installation stucks.
**Screenshots**
![image](https://user-images.githubusercontent.com/56320171/107261362-49062700-6a50-11eb-89fd-cf7c6f7b7e1d.png)
![image](https://user-images.githubusercontent.com/56320171/107260667-68508480-6a4f-11eb-8ea8-892838b3fd03.png)

**Desktop**
 - OS: Arch
-  Game: Rocket League

**Comment by flavioislima** [comment]
Hmm. Have you tried running with a bigger amount of workers? Check the Heroic Config.

**Comment by flavioislima** [comment]
Closing this since had no answer. 
Feel free to reopen if the issue persists @realsontaran

**Comment by realsontaran** [comment]
Sorry for the late response. I tried it with 8 workers, but there was no change.

**Comment by realsontaran** [comment]
I can't cancel the installation as well

**Comment by flavioislima** [comment]
@realsontaran try to download it using legendary only then to see if it works because I could not replicate the issue.

**Comment by realsontaran** [comment]
It looks like problem was in legendary from the very beginning :(

**Comment by flavioislima** [comment]
can you try opening an issue for then or maybe talking to then on their discord
