### ISSUE TITLE
Game status update

### ISSUE THREAD

**Issue by chernyaknikita** [flavioislima/HeroicGamesLauncher#15]
After Legendary said that installation was finished there wasn't any signes of that on the game page inself. If I go to the library and click the game again everything's fine. I guess the page should be reloaded after installation automaticly so it has proper status.

**Comment by flavioislima** [comment]
For sure1
Now we have a dedicated UX/UI designer so we are discussing those things and this will be addressed on the next releases.:)

**Comment by Kazer67** [comment]
Can confirm the issue on Pop!_OS with the .deb package, I install a game, it get stuck at :


![Capture d’écran du 2021-01-07 20-35-18](https://user-images.githubusercontent.com/45577220/103936769-25398380-5128-11eb-856c-066cb6b94a33.png)

I then close xterm, the page stay with the install button present but if I go back to the library and reload, game finally shows as installed and the play button is present.

**Comment by flavioislima** [comment]
@Kazer67 The issue will be solved on the next release that will be out tomorrow.

**Comment by flavioislima** [comment]
Fixed on the new release:
https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/v1.0.0
