### ISSUE TITLE
Game Arguments Not Being Saved

### ISSUE THREAD

**Issue by Eireocean** [flavioislima/HeroicGamesLauncher#154]
Good Day,

I play RDR2 on Steam uisng Proton and use the following launch arguments :

`WINEDLLOVERRIDES=dxgi=n,b PULSE_LATENCY_MSEC=60 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command% -vulkan -width 2560 -height 1440 -USEALLAVAILABLECORES -cpuLoadRebalancing -ignorepipelinecache`

In the Launcher I selected :

```
Wine Version : Proton 5.13
Advanced Options : WINEDLLOVERRIDES=dxgi=n,b PULSE_LATENCY_MSEC=60 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
Game Arguments : -vulkan -width 2560 -height 1440 -USEALLAVAILABLECORES -cpuLoadRebalancing -ignorepipelinecache
```

Note I do have two copies of RDR2, one being Steam one being Epic Games. The Launcher is not saving my Game Arguments, it just voids it.

Regards

**Comment by flavioislima** [comment]
When you run heroic from the terminal, what's the output of the launch arguments?

**Comment by Eireocean** [comment]
Maybe I missed something ... can I launch a game from the command line ?

**Comment by flavioislima** [comment]
Run Heroic from the command line. Then launch a game, on the command line Heroic will show you the Launch Command. You can even copy paste the command on a terminal and launch the game from there

**Comment by Eireocean** [comment]
Here is what I get :

$ WINEDLLOVERRIDES=dxgi=n,b PULSE_LATENCY_MSEC=60 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json  PULSE_LATENCY_MSEC=60  STEAM_COMPAT_DATA_PATH='/home/shaun/.wine' /usr/bin/gamemoderun /usr/lib64/heroic-games-launcher-bin/resources/app.asar.unpacked/build/bin/legendary launch Heather  --no-wine --wrapper "'/home/shaun/.local/share/Steam/steamapps/common/Proton 5.13/proton' run"
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Heather...
gamemodeauto: 
[shaun@localhost ~]$ gamemodeauto: 
esync: up and running.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Unhandled page fault on read access to 0000000000000000 at address 0000000181DE0117 (thread 022c), starting debugger...

**Comment by flavioislima** [comment]
Post command goes on the Launch Arguments on the Other Settings.
As far as I can see the arguments are working. Try to add the other ones now.

**Comment by Eireocean** [comment]
Hi,

I do copy / paste there but they do not save. Hence the opening this issue.

Regards

**Comment by flavioislima** [comment]
Can you look at the config file?
It is on `.config/heroic/GamesConfig/Heather.json` if thats the app name.

**Comment by Eireocean** [comment]
Managed to get it to save this time as I put in under the game itself and
not in the general area. The game did not start though but that is a
different story altogether. Thanks

**Comment by flavioislima** [comment]
Yeah, this kind of option will only work if you use the arguments under the game settings. I'll remove the launch arguments from the General settings since it does not make sense there.

**Comment by flavioislima** [comment]
Removed on the main branch, the next release won't have the option under the Global Settings anymore.
