### ISSUE TITLE
Proton path invalid

### ISSUE THREAD

**Issue by Goggo66** [flavioislima/HeroicGamesLauncher#155]
**Describe the bug**
When selecting Proton as the Wine version to use, an invalid path to the proton executable is created. The game does not start (of course).

**To Reproduce**
1. Replace the directory $HOME/.config/heroic/proton with a symlink to the directory where the Proton versions are stored (in my case, $HOME/.steam/steam/steamapps/common/)
2. (Re-)start Heroic Games Launcher.
3. Go to the Wine settings of an arbitrary game, select the Wine version drop-down box, and observe that the Proton versions are correctly picked up.
4. Select a Proton version, e.g. "Proton - Proton 5.13"
5. Return and start the game by clicking "PLAY NOW".
6. The game does not start.

**Expected behavior**
The game should start with the selected Proton version.

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version 20.10
 -  Game: any
 -  Wine/Proton version: Proton, any version

**Additional context**
Checking the config file of the game, I noticed that the path to the Proton executable is invalid:

```
    "wineVersion": {
      "name": "Proton - Proton 5.13",
      "bin": "'/home/gordon/.config/heroic/tools/protonProton 5.13/proton'"
```
There should be a "/" between "proton" and "Proton 5.13".
After manually adding the "/" and saving the config file, the game starts as expected.

**Comment by flavioislima** [comment]
The idea of this directory is for you to symlink the proton folders to it. In your case the folder was replaced. Try to create a link of the proton folder you want to use to the heroic one.

**Comment by Goggo66** [comment]
Ok, so I restored the proton folder, and created a symlink at .local/share/Steam/steamapps/common to .steam/steam/steamapps/common. That works as expected.
Thanks for your help.
