### ISSUE TITLE
Add a prompt about not enough space to install game.

### ISSUE THREAD

**Issue by lol28** [flavioislima/HeroicGamesLauncher#156]
Add a prompt about not enough space to install game. I was unable to start downloading game until a realized that there's no space enough for it. Until that all i got from Heroic is "Game imported". Would be good if launcher notify us about that.

**Comment by flavioislima** [comment]
Hi!

Makes sense, I'll try to add this check on next release.

**Comment by lol28** [comment]
Thanks!
