### ISSUE TITLE
Can't strart, even after backup or repairing files.

### ISSUE THREAD

**Issue by Kunfuzzle32** [flavioislima/HeroicGamesLauncher#169]
I was playing Rocket League earlier today and it was working fine, until tonight when I tried to launch it, it would load for a few seconds and then stop. The logs show,
`[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Sugar...
00f4:fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
00f4:fixme:toolhelp:Heap32ListFirst : stub
00f4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00f4:fixme:faultrep:ReportFault 00000000005EE380 0x0 stub
` 
After I backed up to a prior version of my desktop and it still would not run, I've tried restarting, repairing, and uninstalling and nothing seems to work. Im using wine 6.1.

**Comment by Kunfuzzle32** [comment]
Seems like it had something to do with wine 6.1 vs. wine 6.0, switched to proton 5.13 and it works now!

**Comment by bill88t** [comment]
Well for me Rocket league doesn't start at all after the 1.5.1 update. Under no wine environment. Also proton isn't even detected on my installation.

**Comment by Kunfuzzle32** [comment]
Have you downloaded proton from steam. You need to go to library then
search by tools and type in proton.

**Comment by flavioislima** [comment]
> Well for me Rocket league doesn't start at all after the 1.5.1 update. Under no wine environment. Also proton isn't even detected on my installation.

Did you tryed to change your settings? With different wine versions or a new prefix? Try also to I stall dxvk on it. 

About proton, you can download from steam, just make sure that you install it on your home folder. Another thing is that you can download other proton versions and extract then on .config/heroic/proton folder.

**Comment by flavioislima** [comment]
@bill88t if that's not trouble for you, try also to remove the .config/heroic folder, then it will regenerate the whole config.
If Rocket League asks to update, say yes only if you're on the game page. On the game card it will work but you wont see any visual feedback of the update. It is a bug that I'll fix soon.
