### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by D3SOX** [flavioislima/HeroicGamesLauncher#174]
**Describe the bug**
All icons are displayed as their name instead of the actual icon

**To Reproduce**
I'm not entirely sure

**Expected behavior**
Icons should be displayed

**Screenshots**
![a](https://user-images.githubusercontent.com/24937357/108397398-35a94780-7218-11eb-988f-44ab4c1e40da.png)
![b](https://user-images.githubusercontent.com/24937357/108397410-37730b00-7218-11eb-9835-617d86ed4691.png)

**Desktop:**
 - OS: Arch Linux
 - Version: 1.5.2 (from AUR `heroic-games-launcher-bin`)

**Additional context**
I don't know why it happens but anyway I think it would be better to bundle the font assets instead of importing them like here:
https://github.com/flavioislima/HeroicGamesLauncher/blob/f7c89b678b6024d70c60769e7eabb77c1e1be18b/public/index.html#L6-L10

I tried to debug it but I got `/bin/sh: line 1: nf: command not found` and I don't remember how to fix this

**Comment by flavioislima** [comment]
Makes sense and I started to bundle all icons but this never happened to me.
Can you try to install it again or maybe remove (or just move) the folder .config/heroic?
Maybe be something really weird with your instalation. Also, it was working before 1.5.2?

**Comment by D3SOX** [comment]
Deleting `~/.config/heroic` doesn't help.
I tried to roll back to `1.4.0`, also without success

**Comment by flavioislima** [comment]
So maybe your internet, firewall or something, is blocking those URLs. 🤔 

I'll create a task to bundle all icons with the App. But now only on the next release.
I'm not planning another bugfix for 1.5 unless something really big appears.

**Comment by flavioislima** [comment]
Btw nf is foreman, it should be on the dev dependencies. But in case it doesnt work. Install it with:
`npm i -g foreman`

**Comment by D3SOX** [comment]
I also thought about something is blocking the URLs but I checked my Pi-hole and the URLs are not blocked:
![a](https://user-images.githubusercontent.com/24937357/108402523-ef56e700-721d-11eb-8864-95f3b947ef80.png)
And I can surely connect to that server:
![b](https://user-images.githubusercontent.com/24937357/108402633-144b5a00-721e-11eb-9d2f-9d4952a0c868.png)

**Comment by D3SOX** [comment]
> Btw nf is foreman, it should be on the dev dependencies. But in case it doesnt work. Install it with:
> `npm i -g foreman`

Thanks I'll try to debug it later

**Comment by D3SOX** [comment]
Yes it is actually blocking those requests
![a](https://user-images.githubusercontent.com/24937357/108405004-d8fe5a80-7220-11eb-9853-3b1387129dff.png)

Adding `(\.|^)fonts\.gstatic\.com$` to the Pi-hole whitelist solved it. (idk why it wasn't found it in any blocklist)
![b](https://user-images.githubusercontent.com/24937357/108406053-262efc00-7222-11eb-806c-dd04eaf6b532.png)



So please consider this as a feature request to bundle the fonts locally. I think it would be better in any case.

**Comment by flavioislima** [comment]
Like I said on #175. 
If you have some time, you can replace the icons with the ones you can download from Ionicicons as SVG and use them the same way I did with the Play/Install/settings Icons on the card. Just send me the PR 😄

**Comment by D3SOX** [comment]
I found `@material-ui/icons` on [npm](https://www.npmjs.com/package/@material-ui/icons) which provides React Components for material design icons.
Would you mind if I replace the Google Font import with those?

**Comment by flavioislima** [comment]
> I found `@material-ui/icons` on [npm](https://www.npmjs.com/package/@material-ui/icons) which provides React Components for material design icons.
> Would you mind if I replace the Google Font import with those?

No, I'm using them in another project and they are fine. Can go with it 👍🏽

**Comment by D3SOX** [comment]
Btw I found out the root cause why they got blocked.
I'm using [hectorm/hblock](https://github.com/hectorm/hblock) which uses [lightswitch05/hosts](https://github.com/lightswitch05/hosts) (as seen in [SOURCES.md](https://github.com/hectorm/hblock/blob/master/SOURCES.md)) and it's a [known issue](https://github.com/lightswitch05/hosts#google-fonts)

**Comment by flavioislima** [comment]
> Btw I found out the root cause why they got blocked.
> I'm using [hectorm/hblock](https://github.com/hectorm/hblock) which uses [lightswitch05/hosts](https://github.com/lightswitch05/hosts) (as seen in [SOURCES.md](https://github.com/hectorm/hblock/blob/master/SOURCES.md)) and it's a [known issue](https://github.com/lightswitch05/hosts#google-fonts)

I see. Good to know.
