### ISSUE TITLE
How can I translate the applications?

### ISSUE THREAD

**Issue by ArturWroblewski** [flavioislima/HeroicGamesLauncher#18]
If the feature exists, there will be plenty of volunteers to help.

I have a request to use the .po files. They make the translation very easy. Application example:
https://github.com/sharkwouter/minigalaxy

**Comment by flavioislima** [comment]
HI! Would be nice to have translations. 
I'm planning to add a simple way of adding new ones soon but right now there is no support for it.

**Comment by flavioislima** [comment]
@ArturWroblewski Heroic is ready to receive translations. If you want to know how to do it, you can use this Pull Request as an Example:
https://github.com/flavioislima/HeroicGamesLauncher/pull/145

**Comment by adityaruplaha** [comment]
This information should be in the wiki, marking as `documentation`.

**Comment by BiRo96** [comment]
I already wrote this documentation in my fork, if you would like to put it on wiki: 
https://github.com/BiRo96/HeroicGamesLauncher/wiki
It's sad, that you can clone a wiki, but can't start a wiki pull request 😞

**Comment by adityaruplaha** [comment]
@BiRo96 many thanks! This info is now on the wiki.
