### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by D3SOX** [flavioislima/HeroicGamesLauncher#182]
**To Reproduce**
See screen records

**Expected behavior**
In the first video it should stay the same
In the second: I'm not sure if the header is intentional

**Screen records**

https://user-images.githubusercontent.com/24937357/108539933-e549ec80-72e0-11eb-91b9-e8a71db3fc18.mp4

https://user-images.githubusercontent.com/24937357/108539938-e67b1980-72e0-11eb-8eb7-b2e713ad4846.mp4

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.5.2

**Comment by flavioislima** [comment]
The first one is new for me but the second one I fixed already in my current branch.
The second one should be simple, just need to set a fixed width for the help box

**Comment by flavioislima** [comment]
The header was fixed here: https://github.com/flavioislima/HeroicGamesLauncher/pull/183/files#diff-092b2bf0646c9c297e8677b8e0e561921caf0c95bd5de4b80bb1b301168d0296R126

So now I'm getting the game name from the game itself instead of passing as a prop.
