### ISSUE TITLE
Game path selection

### ISSUE THREAD

**Issue by D3SOX** [flavioislima/HeroicGamesLauncher#19]
Paths with a space are not correctly passed to legendary (I selected `/home/nico/Games/epic-games-store/drive_c/Program Files/Epic Games`)
![screen](https://user-images.githubusercontent.com/24937357/103724881-a8969000-4fd5-11eb-9d77-34d768cb46fb.png)

Also it would be nice to have an option not to specify the game path (just like running `legendary install [gameid]`

**Comment by flavioislima** [comment]
HI! The latest version fixes this bug, can you try it?

**Comment by D3SOX** [comment]
I can confirm that it works now! Did you see my feature request below the image?

**Comment by flavioislima** [comment]
> I can confirm that it works now! Did you see my feature request below the image?

I did, I'll add more options to the install menu.

**Comment by flavioislima** [comment]
Fixed on the new release:
https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/v1.0.0
