### ISSUE TITLE
Installing FORTNITE

### ISSUE THREAD

**Issue by Vitali64GitHub** [flavioislima/HeroicGamesLauncher#190]
**the bug**
When I install Fortnite, it just won't install on heroic, I found that it is because Legendary was asking what features to install.

**To Reproduce**
1. Fire up HEROIC
2. Install Fortnite
3. Nothing happens

**Expected behavior**
Heroic asking what feature of Fortnite to install

**Desktop:**
-  OS: xUbuntu 20.04
-  heroic ver : 1.4
-  Game: Fortnite
-  Wine/Proton version: Wine-5.0

**Comment by flavioislima** [comment]
Hi. This was already discussed. Fortnite doesn't work on Linux and I have no plans to support selective download soon.

I might in the future blacklist it to not appear on the library. 

 So I'll close this issue for now.

**Comment by Vitali64GitHub** [comment]
> I have no plans to support selective download soon

Why ?

**Comment by flavioislima** [comment]
Besides fortnite the only games that have this is cyberpunk 2077. And it will be a lot of effort on my part and heroic is already taking a lot of my free time, this is an open source project that I basically run alone with one or other contribution from other devs. So I think you know what I mean. I need to focus on stability and most important features at first.

**Comment by Vitali64GitHub** [comment]
Okay, Good Luck ! I really think your game launcher is awesome !

**Comment by flavioislima** [comment]
Thanks, man!

Eventually, I'll add support for this but since it is only for one game I'll focus on making the core better and stable for now!
