### ISSUE TITLE
add ~/ to help file location

### ISSUE THREAD

**Issue by Taza53** [flavioislima/HeroicGamesLauncher#191]
![image](https://user-images.githubusercontent.com/34032665/108601352-70d48380-739c-11eb-9872-4b01d5fadca9.png)

to 
~/.config/heroic/Tools/wine
~/.config/heroic/Tools/proton
~/.local/share/Steam/compatibilitytools.d
~/.local/share/Steam/steamapps/common
~/.local/share/lutris/runners/wine
~/.var/app/com.valvesoftware.Steam (Steam Flatpak)

**Comment by flavioislima** [comment]
done
