### ISSUE TITLE
Autorefresh games library

### ISSUE THREAD

**Issue by CTRL-ALT-DEL-92** [flavioislima/HeroicGamesLauncher#192]
Dear Heroic Developer,

I recently added rage 2 to my library, I got it for free on epic games store through your app. The process went well I browsed the store and completed the purchase flawlessly. The problem is that rage 2 was not shown in my games library, until I manually selected to refresh my games library. My request is: could be possible to add a library refresh command at heroic startup, to automatically add new games?

**Comment by flavioislima** [comment]
Hi!

The idea is good but unfortunately impossible to do it since the epic store itself does not send any command to heroic or legendary, that's why it needs to be refreshed manually. Any game you get for free or buy will require the library to be refreshed.
