### ISSUE TITLE
Show information about the game before installing it

### ISSUE THREAD

**Issue by Ahmed-E-86** [flavioislima/HeroicGamesLauncher#193]
When I install a game using legendary, it gives me the download size and install size of the game. Also, it gives me a warning if I do not have enough free space, or if the game does not work offline. That does not happen with Heroic, it just installs the game without giving me any information about the game.

**Comment by flavioislima** [comment]
That would be good. But legendary does not have a api to give that info to heroic so all information we get on the frontend are shown after executing the command.
I'm not saying that this would be impossible and would like to have it, but I'm limited to the output and it is not possible to interact with the cli as far as I know. 
Even the official epic store does not show that kind of info like the download size, etc. Last time I used it.

**Comment by flavioislima** [comment]
I'm closing this one since now Heroic has a message about free space and also the game requirements are on the game page.
I think it covers most of the things for now.
