### ISSUE TITLE
Some games aren't listed in my library

### ISSUE THREAD

**Issue by benthetechguy** [flavioislima/HeroicGamesLauncher#196]
**Describe the bug**
Some games like Battlefront II that are in my library do not appear in the launcher's library list.

**To Reproduce**
Look in the games library and find games that you know you own, but don't appear in the library.

**Expected behavior**
All games show up in the launcher's library.

**Desktop (please complete the following information):**
 - OS: Manjaro
-  Game: Battlefront II

**Comment by MauricioFIUBA** [comment]
Duplicated from [#48](https://github.com/flavioislima/HeroicGamesLauncher/issues/48)

**Comment by wiryfuture** [comment]
Sorry @benthetechguy there's nothing we can do about this; if legendary doesn't give us the game, we can't show it. You're better off going to the legendary repo to report this.

**Comment by flavioislima** [comment]
Yeah, battlefront and other Origin games won't work on heroic.
