### ISSUE TITLE
[UI/UX] Show game Installed Size, Recommended Specs, etc on the game download page. 

### ISSUE THREAD

**Issue by adityaruplaha** [flavioislima/HeroicGamesLauncher#207]
Upon clicking the game, it should show the detailed description, recommended specs, Developer, Publisher, etc. like on epicgames.com. 
I personally think the installed size is one of the key things that's missing from the App UI currently. It would streamline user experience significantly if they could see how much space they need before they download.

**Comment by flavioislima** [comment]
The PR was merged into Main. So the features will be available on next release.
