### ISSUE TITLE
Define CONTRIBUTING guidelines and coding style guidelines.

### ISSUE THREAD

**Issue by adityaruplaha** [flavioislima/HeroicGamesLauncher#209]
As this repo continues to grow and attract more contributors, I think it will be helpful if coding guidelines, source control guidelines and style guidelines are provided to new wannabe contributors like myself. :)

This includes things like: trailing newlines, indent size, the formatter to use, rebase-over-merge, stuff like that.

**Comment by Nocccer** [comment]
This is a great idea. Also if more people are involved in development, implementing tests (in my eyes) are necessary, too.

**Comment by flavioislima** [comment]
Nice.
Do you have any examples that we can use, some other open-source projects out there?

**Comment by adityaruplaha** [comment]
I'll have to see. Even if we don't, I might just write some myself :P.
