### ISSUE TITLE
conflict with vscodium

### ISSUE THREAD

**Issue by zany130** [flavioislima/HeroicGamesLauncher#215]
don't  know if this is the right place to report it but the rpm package conflicts with the rpm package of  [vscodium](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo)
```
Error: Transaction test error:
  file /usr/lib/.build-id/14/512ca58e91f1940ba8e68d620c03e13cfb7d82 from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/1c/1eccea7fe32b13593eb32f999fc3ce90432239 from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/63/e57a96064e30d496ce9596cb5861ce64f52160 from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/66/c77539c4ab0def65c2f355188fe71bff7b602d from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/74/589964965a9efc95d3e4202f7fc6a7226b6e78 from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/76/90a7dcb40a4a052fdfb0f46a0dbeabbdf6df47 from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
  file /usr/lib/.build-id/a7/97d3b4a5fac6864fda3d230e3ac9104d624990 from install of heroic-games-launcher-bin-1.5.4-1.fc33.x86_64 conflicts with file from package codium-1.53.2-1613090035.el7.x86_64
```

**Comment by flavioislima** [comment]
Hmm. I don't know why.

Maybe @tim77 could help us with that.

**Comment by tim77** [comment]
Sorry for some delay here. It's known issue for Electron apps in Fedora and this could fixed by disabling generating build-id's. This change https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo. Should been fixed in `1.5.5-2` update. Please check and tell is this fixed your issue.

**Comment by tim77** [comment]
> latest rpm file in the releases

This fixed in COPR [1] build only and i am not sure could this even fixed in electron-builder when generating rpm's.

[1] https://copr.fedorainfracloud.org/coprs/atim/heroic-games-launcher/

**Comment by zany130** [comment]
> > latest rpm file in the releases
> 
> This fixed in COPR [1] build only and i am not sure could this even fixed in electron-builder when generating rpm's.
> 
> [1] https://copr.fedorainfracloud.org/coprs/atim/heroic-games-launcher/

tried from there too same issue
