### ISSUE TITLE
Xterm installed

### ISSUE THREAD

**Issue by CleoMenezes** [flavioislima/HeroicGamesLauncher#22]
Why does it installs Xterm terminal?

**Comment by chernyaknikita** [comment]
To log in. But no more Xterm will be needed [soon](#21).

**Comment by flavioislima** [comment]
Yeah, on the next release we won't need a terminal anymore for anything, neither login or install games :D

**Comment by CleoMenezes** [comment]
Pretty good!

**Comment by flavioislima** [comment]
Fixed on the new release:
https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/v1.0.0
