### ISSUE TITLE
Uninstalled game thinks it's installed

### ISSUE THREAD

**Issue by RD1K** [flavioislima/HeroicGamesLauncher#225]
At some point, I tried to install Rocket League via Heroic Games Launcher. There was some issue, and then I made the mistake of deleting the folder that contained the game directly instead of uninstalling with Heroic. Now, Heroic still thinks that the game is installed even though the folder it's "installed" to no longer exists. I've tried repairing and updating the game, but it doesn't work. I've also tried clicking uninstall so I can reinstall, but that doesn't work either. So, what can I do to properly install the game?

 - Manjaro Linux
 - Nibia 20.2.1
-  Game: Rocket League
-  Wine/Proton version: Proton 5.0

**Comment by flavioislima** [comment]
Hi! I had this issue myself before and we will have an option to force uninstall in the future.
For now. Go to the file: `.config/legendary/installed.json`. And remove the entry for the rocket league game.

After that, reload heroic and it will be gone.

**Comment by RD1K** [comment]
That worked, thank you so much!
