### ISSUE TITLE
"appimaged" shows "Invalid desktop file" notification

### ISSUE THREAD

**Issue by kcthrn** [flavioislima/HeroicGamesLauncher#228]
**Describe the bug**
[appimaged](https://github.com/probonopd/go-appimage) gives "Invalid desktop file" notification when Heroic is launched.

**To Reproduce**
1. Install appimaged
2. Download Heroic AppImage into either $HOME/Applications or $HOME/Downloads
3. Let appimaged detect and integrate Heroic into the system
4. Launch Heroic

**Expected behavior**
No notification

**Desktop (please complete the following information):**
 - Version 1.5.5 (and previous versions [1.4.x, 1.3.x, ...])

**Additional context**
The notification is annoying because it doesn't time-out. I have to close it every time I launch Heroic.

Contents of `.desktop` file generated by `appimaged` is similar to #99.

I also believe bug is related to #128 as the line referenced in #128 is still present in [this file](https://github.com/flavioislima/HeroicGamesLauncher/blob/8d17e4479f5be4a34d2591beec639b1b410278c1/package.json#L37).

**Comment by flavioislima** [comment]
This bug supposed to be gone but for some reason the desktop line was back on package.json. 🤦🏽‍♂️

Thanks I'll remove it on next release.
