### ISSUE TITLE
How select proton instead of wine

### ISSUE THREAD

**Issue by andirsun** [flavioislima/HeroicGamesLauncher#23]
I have steam installed with proton but I cant select proton instead of wine in games settings.

**Comment by flavioislima** [comment]
@andirsun Just added a comment on the release pages. For now we are getting the proton version from compatibilitytools.d on the steam/root folder.

If you want to use the other Proton version, for now, do a symlink like this:
`ln -s $HOME/.steam/root/steamapps/common/Proton\ 5.0/ $HOME/.steam/root/compatibilitytools.d/`

I'm working on getting all proton versions for the next release.

**Comment by andirsun** [comment]
Thanks for help, but I have a flatpak version of steam and dont see the ~.steam/ folder.

**Comment by flavioislima** [comment]
For Flatpak Steam is probably in your $HOME/.var/app folder.
Check there, please. I haven't tested with Flatpak yet.

**Comment by andirsun** [comment]
Solved with the 1.0 version thanks. !
