### ISSUE TITLE
Folder for installation can not be selected

### ISSUE THREAD

**Issue by gituser823** [flavioislima/HeroicGamesLauncher#235]
**Describe the bug**
Folder for installation can not be selected, when trying to install a game.

**To Reproduce**
    Try to install a game

    It opens the folderselectiontool.

    No folder can be selected in the end.

**Expected behavior**
Be able to select a folder

**Screenshots**
![legendary](https://user-images.githubusercontent.com/32219087/110224361-2f36f300-7edb-11eb-8f70-4fc038965a5c.gif)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20 Ulyana
-  Game: any
-  Wine/Proton version: wine 5.0

**Additional context**
Using Cinnamon Desktop.
I am also using legendary and reported the bug there, but they said its HeroicGameLauncher related.

**Comment by flavioislima** [comment]
I guess this is happening when installing from the library. Can you try on the game page?

**Comment by gituser823** [comment]
From the game page it works, thanks.

**Comment by flavioislima** [comment]
> From the game page it works, thanks.

so it is an issue on the gamecard, weird!

**Comment by LukeVader-IV** [comment]
i just want to add it seems to work if you select a file like "api-ms-win-core-console-l1-1-0.dll" it seems to work
