### ISSUE TITLE
Changing default installation path has no effect

### ISSUE THREAD

**Issue by Beanow** [flavioislima/HeroicGamesLauncher#25]
While I've set the default install path under settings to `/mnt/storage/Games-Heroic`, selecting "Install on default path" when installing the games wind up under `~/Games/Heroic`.

Using "install on another path" does allow installing to the preferred path.

Tested with v1.0 deb package on Ubuntu 18.04.

**Comment by serjor** [comment]
Same here using Manjaro

**Comment by flavioislima** [comment]
Fixed on latest release
