### ISSUE TITLE
MangoHUD Does Not Work

### ISSUE THREAD

**Issue by intelligentgaming** [flavioislima/HeroicGamesLauncher#28]
Adding the MANGOHUD=1 argument does not enable MangoHUD, and to rule out MangoHUD, I also tried using DXVK_HUD=1 which also does not work. 

Kubuntu 20.10 and MangoHUD installed from PPA which works with game ran through Steam and Proton.

**Comment by flavioislima** [comment]
Do you have DXVK installed on your prefix?
Mangohud works only if you have DXVK or VKD3D.

**Comment by intelligentgaming** [comment]
> Do you have DXVK installed on your prefix?
> Mangohud works only if you have DXVK or VKD3D.

Pretty sure, I do, considering it works with both games launched through Steam Proton and Lutris. 

To rule it out, I changed the default Wine Version (Settings) to both Proton-GE and a version of Lutris Wine, neither of them worked either.

**Comment by flavioislima** [comment]
No, I mean, are you using the same wine prefix folder? because if you create a new wine prefix, even if you use Proton-GE, it won't work.

Are you adding other options or only MANGOHUD=1?
I just tested again with another game and it is working for me.

**Comment by intelligentgaming** [comment]
> No, I mean, are you using the same wine prefix folder? because if you create a new wine prefix, even if you use Proton-GE, it won't work.
> 
> Are you adding other options or only MANGOHUD=1?
> I just tested again with another game and it is working for me.

OK, I'll manually install it tonight when I get home from work. 

I presume I just follow the instructions here - https://github.com/doitsujin/dxvk

I normally don't need to do this as I use Steam with Proton and Lutris with Lutris Wine.

But just to clarify, installing Heroic does NOT install DXVK into your default Wine prefix, so instead you are running Epic Games using the system installed Wine without DXVK.

**Comment by flavioislima** [comment]
> > No, I mean, are you using the same wine prefix folder? because if you create a new wine prefix, even if you use Proton-GE, it won't work.
> > Are you adding other options or only MANGOHUD=1?
> > I just tested again with another game and it is working for me.
> 
> OK, I'll manually install it tonight when I get home from work.
> 
> I presume I just follow the instructions here - https://github.com/doitsujin/dxvk
> 
> I normally don't need to do this as I use Steam with Proton and Lutris with Lutris Wine.
> 
> But just to clarify, installing Heroic does NOT install DXVK into your default Wine prefix, so instead you are running Epic Games using the system installed Wine without DXVK, unless you manually select another Wine options such as Proton-GE or Lutris Wine.

If you Use Lutris or Steam it might not notice because everything is automated, and I think I'll do the same way as they do when creating a new prefix, but Proton, Wine, DXVK are different projects and no Proton contains a fixed version of DXVK installed, they are independent because this permits that you could use any DXVK version with any Wine/Proton version as well. 

On Lutris there is a config for you to choose the different DXVK versions, if disable it, you will notice that even with Proton-GE, mangohud will stop working, unless dxvk is already installed manually on the prefix.

So right now, on Heroic, I'm not installing DXVK on newer prefixes, you need to add manually using winetricks. You need to choose the folder for the wineprefix and then open winetricks on the settings page and install dxvk (latest). This way Mangohud will work.

But I'll think about doing this automatically soon since DXVK is needed for most games, as well as VKD3D for some DX12 games.

**Comment by intelligentgaming** [comment]
> > > No, I mean, are you using the same wine prefix folder? because if you create a new wine prefix, even if you use Proton-GE, it won't work.
> > > Are you adding other options or only MANGOHUD=1?
> > > I just tested again with another game and it is working for me.
> > 
> > 
> > OK, I'll manually install it tonight when I get home from work.
> > I presume I just follow the instructions here - https://github.com/doitsujin/dxvk
> > I normally don't need to do this as I use Steam with Proton and Lutris with Lutris Wine.
> > But just to clarify, installing Heroic does NOT install DXVK into your default Wine prefix, so instead you are running Epic Games using the system installed Wine without DXVK, unless you manually select another Wine options such as Proton-GE or Lutris Wine.
> 
> If you Use Lutris or Steam it might not notice because everything is automated, and I think I'll do the same way as they do when creating a new prefix, but Proton, Wine, DXVK are different projects and no Proton contains a fixed version of DXVK installed, they are independent because this permits that you could use any DXVK version with any Wine/Proton version as well.
> 
> On Lutris there is a config for you to choose the different DXVK versions, if disable it, you will notice that even with Proton-GE, mangohud will stop working, unless dxvk is already installed manually on the prefix.
> 
> So right now, on Heroic, I'm not installing DXVK on newer prefixes, you need to add manually using winetricks. You need to choose the folder for the wineprefix and then open winetricks on the settings page and install dxvk (latest). This way Mangohud will work.
> 
> But I'll think about doing this automatically soon since DXVK is needed for most games, as well as VKD3D for some DX12 games.

No worries, it would be useful, especially for newbies, plus gaming on Linux kinda requires DXVK nowadays, well for Windows developed games anyways.

**Comment by intelligentgaming** [comment]
Fixed, installed DXVK into the default Wineprefix and now MangoHUD works.

For reference, on Ubuntu based distributions, the default Wine prefix location appears to be /home/%user%/.wine, but I'm not sure if it is the same for Arch based distros. 

Or for me specifically /home/ryan/.wine

**Comment by flavioislima** [comment]
> Fixed, installed DXVK into the default Wineprefix and now MangoHUD works.
> 
> For reference, on Ubuntu based distributions, the default Wine prefix location appears to be /home/%user%/.wine, but I'm not sure if it is the same for Arch based distros.
> 
> Or for me specifically /home/ryan/.wine

AFAIK is the same location on all distros except when using a flatpak version of wine, then I guess it will be on the app folder.

So I'll close the issue and I added a note to add DXVK to install automatically in the future! :D
