### ISSUE TITLE
npm run dist AppImage doeesnt work

### ISSUE THREAD

**Issue by CoffeeBoi47** [flavioislima/HeroicGamesLauncher#3]
running `npm run dist` to build the binaries builds the AppImage fine but running that AppImage opens Heroic with inspect element open and Heroic is blank. Theres no errors if you run it in a terminal and theres no errors in the Heroic inspect element console either. npm start doesnt work either and theres already a issue open for that so I cannot make changes and contribute to the code because if I do I make a change I have no way to run Heroic with the changes I made because well theres no way to run it

**Comment by flavioislima** [comment]
> running `npm run dist` to build the binaries builds the AppImage fine but running that AppImage opens Heroic with inspect element open and Heroic is blank. Theres no errors if you run it in a terminal and theres no errors in the Heroic inspect element console either. npm start doesnt work either and theres already a issue open for that so I cannot make changes and contribute to the code because if I do I make a change I have no way to run Heroic with the changes I made because well theres no way to run it

So I improved the Readme with more information on how to create the packages. I'll close the issue for now.

Thanks!
