### ISSUE TITLE
PPA for .deb?

### ISSUE THREAD

**Issue by leillo1975** [flavioislima/HeroicGamesLauncher#30]
Hi
Is possible to create a PPA repository for ".deb"s? It would be much easier to keep the application updated.

**Comment by flavioislima** [comment]
I'm doing this soon, already have an account and everything but I'll need to setup a ubuntu machine (docker probably) to do all the process because it is the only way.

**Comment by leillo1975** [comment]
Thanks a lot for all your efforts, I appreciate your work!

**Comment by flavioislima** [comment]
@leillo1975 will close this one and we can track it on #78

**Comment by leillo1975** [comment]
First of all, congrats for the 2.0 version, and of course for all your awesome work. Is there any progress on this issue? 
Greetings!

**Comment by imLinguin** [comment]
@leillo1975 Heroic uses third party PPA: `apt-fast`, exact instructions are in the README
