### ISSUE TITLE
Play button doesn't update after game exits

### ISSUE THREAD

**Issue by Beanow** [flavioislima/HeroicGamesLauncher#31]
Whether you close the game normally, kill it manually, or kill through the Heroic UI, the button doesn't update.
It keeps showing "Playing (stop)". Preventing you from launching the game again (as it will try to kill).

!["Playing (stop)"](https://user-images.githubusercontent.com/497556/104183746-b784a480-5412-11eb-9f2b-714f95f018c1.png)

Tested on Ubuntu 18.04, Heroic v1.0.1

**Comment by flavioislima** [comment]
Yeah, confirmed the issue. It happened on my latest refactoring of the GamePage. I'll fix on the next release.
by the way, the game is killed when the button is pressed, but the status does not change.

Thanks!

**Comment by flavioislima** [comment]
@Giovix92 can you test again on the latest release 1.0.2?

**Comment by Beanow** [comment]
With v1.0.3 it's a little too eager to update :sweat_smile:.
With the game still running it reverts back to "Play now". It behaves strangely in that sometimes pressing Play now with the game running it will kill. Sometimes it launches a second instance.

**Comment by flavioislima** [comment]
> With v1.0.3 it's a little too eager to update .
> With the game still running it reverts back to "Play now". It behaves strangely in that sometimes pressing Play now with the game running it will kill. Sometimes it launches a second instance.

Yeah, this needs to be improved in the future.
The flow is as follows:
Starts game > Game opens > if you close/kill the game manually it will take some time to have the response back that the process is finished and then will return to the Play status. But that depends on how long does it takes to have the response.
If you click the Stop button, it sends the kill signal, waits for the game to be closed, and then returns to the play status. 

This should work for most cases but can behave differently depending on how the system will kill the process and we know that it can be different depending on the case. Some process hangs when asked to close, some close immediately.
Even in Lutris I noticed this, and I think their approach is more mature probably than mine.

**Comment by Beanow** [comment]
Well, in my case what I did was:
- Launch the game with the play button. (It changes to stop before game splash screen, as expected).
- Wait a few moments for game to go full screen.
- Alt+Tab back to Heroic, and it's already showing play now, before attempting to exit/kill the game.

**Comment by flavioislima** [comment]
> Well, in my case what I did was:
> 
> * Launch the game with the play button. (It changes to stop before game splash screen, as expected).
> * Wait a few moments for game to go full screen.
> * Alt+Tab back to Heroic, and it's already showing play now, before attempting to exit/kill the game.

I see. So give me more details like wine/proton version and game name. Might be that after the game is launched, it starts others process and the original one gets closed, so then to Heroic, the game was closed.
Also, there is now an option on the game page to check the latest game log.
Attach it here if possible.

**Comment by Beanow** [comment]
Ah, @flavioislima so we're waiting for the process to exit.
Killing works as expected though, so possibly polling the process list if we have the game page open would be more robust. It could handle even weird cases like restarting the launcher while the game is still running.

> I see. So give me more details like wine/proton version and game name.

Running the .deb version, wine `Lutris-5.7-8-x86_64`.

You're right that this game might be creating a new process. Problem occurs with [My Time at Portia](https://www.protondb.com/app/666140). Also tested [Stranded Deep](https://www.protondb.com/app/313120) which works better.

**Comment by flavioislima** [comment]
Thanks. We can improve this, right now I'm just doing a `pkill -f gamename` to kill, which works since it will kill all process with the game name on it. But for checking if the process is still opened I'll need to do more investigation.
I don't really think this is a big issue and does not affect the functionality of the application, so I'll consider the bug fixed and I'll add a note to improve this in the future.

**Comment by Beanow** [comment]
Agreed @flavioislima, the new situation of sometimes having to manually exit/kill the game in case it's inconsistent, is better than not being able to launch games because it wants to kill a game that's not running. Happy to leave this on the backlog.

I spotted the kill-by-name part in the source yeah. Probably a similar counterpart would be `ps | grep` process polling-by-name. But not sure if that's well behaved in something like a flatpack container and various distros.

**Comment by flavioislima** [comment]
> Agreed @flavioislima, the new situation of sometimes having to manually exit/kill the game in case it's inconsistent, is better than not being able to launch games because it wants to kill a game that's not running. Happy to leave this on the backlog.
> 
> I spotted the kill-by-name part in the source yeah. Probably a similar counterpart would be `ps | grep` process polling-by-name. But not sure if that's well behaved in something like a flatpack container and various distros.

Yeah, I'm not sure either. And I think that pkill uses pgrep that is basically a `ps | grep`. I tried different ways as well with different solutions I found across the internet and they all behaved the same when they worked.
