### ISSUE TITLE
Launcher keeps loading and "skips" initial SID code view

### ISSUE THREAD

**Issue by Giovix92** [flavioislima/HeroicGamesLauncher#36]
Hello! Thank you for your effort in this app!

Upgraded freshly from 0.3.1-beta to 1.0.1 (by deleting folders such as .config/heroic and .config/legendary), just to check the new SID code method. Sadly it will just display for a few ms and then keeps loading endlessly.

Running the appimage thru terminal shows this error: https://del.dog/oppuniguxe.txt.

Logging in from 0.3.1-beta and then running 1.0.1 works fine, as expected.

**Comment by Nan123721** [comment]
install legendary and run "legendary auth" and login, then try relaunching Heroic. That at least worked for me!

**Comment by Giovix92** [comment]
> install legendary and run "legendary auth" and login, then try relaunching Heroic. That at least worked for me!

It works too with 0.3.1-beta and then running 1.0.1, as I said earlier though :D

**Comment by flavioislima** [comment]
Hi!
Yeah, just tested and the refactor I did on 1.0.1 broke for some reason the login screen. I'll send a fix today.

Thanks!

**Comment by flavioislima** [comment]
@Giovix92 can you test again on the latest release 1.0.2?

**Comment by Giovix92** [comment]
> @Giovix92 can you test again on the latest release 1.0.2?

Working fine! The only thing that's "left" is that, right after login, if you try to load any game page (eg. Trackmania / Rocket League) it'll just loads endlessly. Maybe I can try again by running it from terminal?

**Comment by flavioislima** [comment]
Yeah, I fixed one thing and broke another. I'm already uploading new files.

**Comment by flavioislima** [comment]
Check now: https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/v1.0.3

**Comment by Giovix92** [comment]
> Check now: https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/v1.0.3

Yep! Working fine! Thank you mate :)

**Comment by flavioislima** [comment]
Nice! :D
