### ISSUE TITLE
Gamemode support

### ISSUE THREAD

**Issue by gsmetal** [flavioislima/HeroicGamesLauncher#37]
It would be cool to have native support of [gamemode](https://github.com/FeralInteractive/gamemode), like it works in Lutris.

**Comment by flavioislima** [comment]
Ok, I'll add to the feature request list.

**Comment by Docmine17** [comment]
Put "gamemoderun" in "Other Launch Options"

**Comment by flavioislima** [comment]
Added option on latest release. Please update :D
