### ISSUE TITLE
Can't see the installation progression

### ISSUE THREAD

**Issue by stemy2** [flavioislima/HeroicGamesLauncher#43]
Hello,

I'm currently installing a game, but the progess seems glitchy, i only see "installing %" with the (supposed) progress bar staying all grey.
![Screenshot_20210113_211053](https://user-images.githubusercontent.com/22192600/104505269-8d321300-55db-11eb-98f4-6b5845429adc.png)

**Comment by flavioislima** [comment]
Hi! I'm closing this one since it is a duplicated of https://github.com/flavioislima/HeroicGamesLauncher/issues/27
I'm looking into that.
