### ISSUE TITLE
Filter games uncompatible with wine

### ISSUE THREAD

**Issue by stemy2** [flavioislima/HeroicGamesLauncher#44]
Hello,

Since we can only download windows version of the games (even whan a linux version actually exists), we have often bad surprises when we discover that our downloaded games aren't working at all with wine. Personally, i just wasted my money buying a game i'm not able to make working because nothing happens when i'm launch it, only wine is launched but not the game.

So a filter could avoid us a such bad surprise.

**Comment by flavioislima** [comment]
There is already a button on the Game Page to Check the Compatibility. 
If you want to check it before buying a game, go to [ProtonDB](https://www.protondb.com/) or winedb.com
