### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Linux4Good** [flavioislima/HeroicGamesLauncher#45]
Hi!

thanks for creating this project.

How can I help with this? Do i need python knowledge or Javascript is enought?

**Comment by flavioislima** [comment]
Hey, thanks for the interest.
There are many ways to contribute to the project with code, testing, etc.

For coding purposes, the code is basically Javascript. On the Frontend is React + typescript and on the 'backend', the Electron part, is NodeJS with Javascript. I'll migrate to Typescript as well when I have some time.

So, you will need to get some knowledge on how Electron works if you don't know, but is not that difficult to understand I used only the documentation to learn and it was ok.

For now, we are using plain CSS but migrating it to SASS.

So feel free to make a fork of the repository and have fun! :D

**Comment by Linux4Good** [comment]
Ok, I did a fork and will try to fix some of the issues we have opened here to getting used to the code.

Thanks for the explanation :smile:

**Comment by Eireocean** [comment]
Good Day,

Is there a debug option when launching games to get some info / feedback. Under Steam I always just had to add PROTON_LOG=1.
The game I am testing I start Heroic from cli, game does not start / display but at the same time does not seem to crash. I can see processes in the background.

Regards

**Comment by adityaruplaha** [comment]
@Eireocean Hi! Sorry for not following up. Please join us over at Discord where we can discuss your request in more detail. Thanks for your interest in this project. :)

Also this information should be in the Wiki, I'm working on it.

**Comment by adityaruplaha** [comment]
Also this was superseded by #223 (which is now a discussion) so I'm going to close this.
