### ISSUE TITLE
suggestion for addding scrollbar

### ISSUE THREAD

**Issue by Rajalolxd** [flavioislima/HeroicGamesLauncher#46]

**Comment by flavioislima** [comment]
HI!

That's funny because I just removed the scrollbar on version 1.0. But I think I'll bring it back because is really complicated to uso only the mouse wheel when you have a large library.

**Comment by lucifertdark** [comment]
Please do add it back, they do actually make life easier when dealing with a larger collection of games that goes off the bottom of the screen. ps has anyone said thank you for what you've done so far? well I am now. :+1:

**Comment by flavioislima** [comment]
I will, don't worry, I also think that it was better with it before. 👍🏽

**Comment by flavioislima** [comment]
Re-added on latest release

Thanks!
