### ISSUE TITLE
Recently added game not appearing in Library

### ISSUE THREAD

**Issue by tuxisagamer** [flavioislima/HeroicGamesLauncher#48]
Just added Battle Front II and the game is not appearing in the Library. I have logged out, refreshed, and even restarted the PC.

**Comment by zineth57** [comment]
Having the same problem, will try your solution

**Comment by Rajalolxd** [comment]
This is a legendary problem

**Comment by lucifertdark** [comment]
> This is a legendary problem

Actually it's more likely an Epic problem as I tried installing it through Lutris with the actual Epic Games Store & it's not working through that either.

**Comment by zineth57** [comment]
> Having the same problem, will try your solution

tried the solution, but it did not work. Origin did not open a window where i could link my egs account to my origin account, it either told me "Sorry, there was an issue redeeming your code. Please try again in a few minutes." or it just asked for a product code, which i do not know where to find.

**Comment by Rajalolxd** [comment]
Try to Run legendary with any game with --dry-run

legendary launch GAME --dry-run

It will Show your info

**Comment by flavioislima** [comment]
Hey guys, I'll close this one since it is a Epic games issue, neither Legendary or Heroic will fix this.
