### ISSUE TITLE
Proton Folder

### ISSUE THREAD

**Issue by paulopaim** [flavioislima/HeroicGamesLauncher#49]
First of all, thanks for this repository, very good job!

Now about my issue, in some linux distributions, like Fedora, the default steam folder is on:
- ~/.local/share/Steam/

and if I install via flatpak it is on:
- ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/

If possible, will be nice to add this folders in the file:
- [ ] utils.js
that way, it can found the proton without problems.

**Comment by Linux4Good** [comment]
Makes sense.
I guess this is something that I can start looking into @flavioislima since it looks like a simple change.

**Comment by flavioislima** [comment]
@paulopaim thanks for sharing those paths, I wasn't really sure about the one for the Steam Flatpak. I just merged @Linux4Good changes on my current work branch and it is working, so you can expect this to work on the next release this weekend.

**Comment by paulopaim** [comment]
Thank you! I thought about making a pull request, but I'm new in code, so I open a issue.
One day I start to contribute.

**Comment by flavioislima** [comment]
@Linux4Good added it and is now on latest release the new path to the flatpak steam version.

@paulopaim don't worry, feel free to clone the repo and try a feel things. If you have any question about the code, let me know. 

Abração!
