### ISSUE TITLE
Please allow custom command for 'wine'

### ISSUE THREAD

**Issue by clebercasali** [flavioislima/HeroicGamesLauncher#53]
I have multiple versions of wine installed, and I've set up scripts to run them. Like 'wine-tkg', 'wine-staging' and 'wine-pba'.
Calling 'wine' will just run vanilla wine for me.
It would be nice if the 'wine' command could be customized.
Even nicer if it could be set per game.

**Comment by flavioislima** [comment]
The thing is that this is not the common way of using wine.
If you want to use custom wine, just create a symlink to each of them on the lutris folder.
Right now we look for different wine versions on the lutris folder and for proton on Steam folder.
The lutris one is: `.local/share/runners/wine`

**Comment by clebercasali** [comment]
It's actually "~/.local/share/lutris/runners/wine".
I've made symbolic links there to my custom wine versions, and it worked.

**Comment by flavioislima** [comment]
Nice 👍🏽
