### ISSUE TITLE
Copr Repo for Fedora

### ISSUE THREAD

**Issue by dvdmuckle** [flavioislima/HeroicGamesLauncher#54]
Similar to #30, it would be great to have a Copr repo for RPM packages. I'm familiar with how Copr works and would be happy to help.

**Comment by flavioislima** [comment]
@dvdmuckle Man, go ahead. I don't know how Copr works, to be honest, I'm more familiar with PPAs and AUR . But if you can keep it updated, this will help a lot the Fedora users. 😄

**Comment by dvdmuckle** [comment]
I'll see if I can set something up. How do you do builds of RPM packages? Copr generally expects to build with a spec file but I could maybe hack something together. It won't be automated unless you can add some webhooks or GitHub actions, but it'll be something.

**Comment by flavioislima** [comment]
All builds are made by the electron-builder. It has all the scripts. But if you need the source to build the RPM file, you maybe could use the tar.xz file to test. If it works, we can set up a github action for that.

**Comment by flavioislima** [comment]
@dvdmuckle let's track this on #78
