### ISSUE TITLE
Flatpak hints

### ISSUE THREAD

**Issue by plata** [flavioislima/HeroicGamesLauncher#6]
**Disclaimer:** I've created the Flatpak for PlayOnLinux 5 (see https://github.com/flathub/org.phoenicis.playonlinux).

- There's an NPM package to build electron flatpaks: https://www.npmjs.com/package/electron-installer-flatpak.
- To run Wine inside the Flatpak, you have to install certain packages and enable some options (e.g. that controllers can be used).
    - https://github.com/PhoenicisOrg/phoenicis/tree/master/phoenicis-dist/src/flatpak (might be a good starting point)
    - https://github.com/winepak/winepak
    - https://github.com/flathub/com.valvesoftware.Steam
- In general: How to handle Wine? Currently, HGL uses the system Wine. For Flatpak this means, that Wine should be part of the Flatpak (like in Winepak). Problem: Different games might need different Wine versions and you must update the used Wine occasionally. With the PoL 5 Flatpak, we do not have this issue because PoL downloads Wine on demand (i.e. when you install an app) from https://www.playonlinux.com/wine/binaries/phoenicis/.

**Comment by flavioislima** [comment]
Thanks @plata , I'll prepare a Flatpak release as soon as the app is more stable.

**Comment by TheEvilSkeleton** [comment]
Also wanted to mention that this one exists as well: https://github.com/fastrizwaan/flatpak-wine

**Comment by flavioislima** [comment]
Lets keep tracking this on #78
