### ISSUE TITLE
How to run with prime-run ?

### ISSUE THREAD

**Issue by aniketfuryrocks** [flavioislima/HeroicGamesLauncher#60]
I am using nvidia-intel hybrid on manajaro. How do I launch the games using prime-run

**Comment by flavioislima** [comment]
I'm not 100% sure but I guess you can add these options here on the settings screen > other > environment variables:
`DRI_PRIME=1  _NV_PRIME_RENDER_OFFLOAD=1  __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only`
