### ISSUE TITLE
Cant use Lutris wine

### ISSUE THREAD

**Issue by Taza53** [flavioislima/HeroicGamesLauncher#64]
Any proton version in the "$HOME/.local/share/lutris/runners/wine" folder can't be used when the default wine prefix is changed.
Before changing the wine prefix it would launch rocket league(the only game i have tested) and would work. To check it further I made syslink of proton-ge-custom to both "$HOME/.local/share/lutris/runners/wine" and "$HOME/.local/share/Steam/compatibilitytools.d" and when I tried to use the Lutris one it failed to launch but the steam one worked.

![image](https://user-images.githubusercontent.com/34032665/104936542-f4b9db00-59ac-11eb-8f72-8ce58247f4a7.png)

using the appimage.

**Comment by flavioislima** [comment]
Can you upload the log file of when you're trying to launch the game? you can use the 'Latest Log' button on the game page to check that.

**Comment by Taza53** [comment]
[cli] INFO: Logging in...
[Core] INFO: Logging in...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Sugar...
gamemodeauto: 
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wineserver: using server-side synchronization.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
XIO:  fatal IO error 4 (Interrupted system call) on X server ":0"
      after 80094 requests (80094 known processed) with 0 events remaining.
gamemodeauto:

**Comment by flavioislima** [comment]
This is not an issue with heroic, this might be some permission with the filesystem, etc.
Heroic is just a frontend to legendary, this error will probably throw using it as well.
But if you want to try, install legendary and copy the Launch command and put it on the terminal, changing only the legendary bin for the one you downloaded.

**Comment by flavioislima** [comment]
One thing that I remembered now. The way it is currently implemented on heroic, you cannot use the proton linked to lutris folder. Because heroic checks if the binary comes from steam and them use the wrapper to run proton, for lutris, it runs the wine inside the bin folder. So if you link proton to lutris, it will use the wine binary instead of the proton one.

I may change this in the future and check only the binary name, but for now it checks if it is Steam or Lutris.

**Comment by Taza53** [comment]
Thanks yeah I dont think the log shows an error as when i cleared the log and tried to run with lutris nothing showed up in logs.
Love heroic, makes my games easier to run and faster.
