### ISSUE TITLE
AppImage does not run with newest OpenSuse Leap 15.2

### ISSUE THREAD

**Issue by linuxnutzer** [flavioislima/HeroicGamesLauncher#66]
The AppImage depends on glibc version 2.27. Unfortunately Leap 15.2 has glibc version 2.26. Is it possible to lower the glibc dependency to 2.26 or include the glibc in the AppImage?

Thank you

Linuxnutzer

**Comment by flavioislima** [comment]
Hmm, weird. Actually, I have no glibc as a dependency on my build file. 
Are you trying to use the AppImage with the AppImage Launcher?
Can you try the RPM installer or the tar.xz file? on the tar.xz just extract it anywhere and run the heroic binary.

**Comment by linuxnutzer** [comment]
Ok, I tested the tar.xz file. Same error.
`Error: Command failed: /home/user/bin/heroic-1.1.1/resources/app.asar.unpacked/build/bin/legendary auth --sid xxxxxxxxx
[6435] Error loading Python lib '/tmp/_MEIBd8ZaV/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: version GLIBC_2.27 not found (required by /tmp/_MEIBd8ZaV/libpython3.8.so.1.0)`

**Comment by flavioislima** [comment]
Like I said on #69, can you try downloading and login with legendary?
https://github.com/derrod/legendary

**Comment by linuxnutzer** [comment]
Hi, I tried the legendary binary. It seems that it contains python 3.8 build with glibc 2.27. That's why it will not run. Unfortunately, Leap 15.2 has only python 3.6. Therefore, it meets not the requirements of the legendary python code :(

**Comment by flavioislima** [comment]
> Hi, I tried the legendary binary. It seems that it contains python 3.8 build with glibc 2.27. That's why it will not run. Unfortunately, Leap 15.2 has only python 3.6. Therefore, it meets not the requirements of the legendary python code :(

Yeah, I did some research and found that legendary is not available for Leap because of the old python there. Maybe if you activate some testing repositories it would work. But it is been a long time since I used OS so I'm not familiar right now on which repos to use and so on. Maybe try to ask on the OS community on reddit maybe.

**Comment by flavioislima** [comment]
I'll close this issue since is not heroic related.
