### ISSUE TITLE
err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.

### ISSUE THREAD

**Issue by SameExpert** [flavioislima/HeroicGamesLauncher#70]
When I launch a Uplay game (`UplayLaunch.exe`), it doesn't launch anything, not any screen. `The PLAYING (STOP)` button automatically becomes back to `PLAY NOW` within few seconds.
Here is the log:
~~~
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Jasper...
0230:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
0230:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC
~~~

Non-Uplay games seem to be working (I just tried one game and it was working).

**Comment by flavioislima** [comment]
This looks like something with wine, and we do not support that. try posting this error on a linux gaming community like reddit. Probably you will need to install some dependencies with winetricks first to make it work.

**Comment by SameExpert** [comment]
I found out what the problem was:


> 0230:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.

This was, because **dxvk** was not set up, though I had **dxvk-mingw-git** installed. This command fixed it:
~~~
setup_dxvk install
~~~



> 0230:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC

This was because **Uplay** was not installed, so the game was getting aborted. I installed **Uplay** via **Winetricks** and the problem got sorted out.

I think that Heroic Game Launcher should do this by default, so other users won't face the same problems.

**Comment by flavioislima** [comment]
> I found out what the problem was:
> 
> > 0230:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
> 
> This was, because **dxvk** was not set up, though I had **dxvk-mingw-git** installed. This command fixed it:
> 
> ```
> setup_dxvk install
> ```
> 
> > 0230:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC
> 
> This was because **Uplay** was not installed, so the game was getting aborted. I installed **Uplay** via **Winetricks** and the problem got sorted out.
> 
> I think that Heroic Game Launcher should do this by default, so other users won't face the same problems.

I see. I don't know if I'm able to fix this on my side. The thing is that Legendary, and consequently, Heroic, is limited to the info we get from Epic. I can take a look at the manifest files, if there is something related to uplay, it is possible to automate the installation, otherwise, the user will need to fix this on their side.

**Comment by flavioislima** [comment]
Closing this one since dxvk is installed automatically now
