### ISSUE TITLE
Doesn't sync

### ISSUE THREAD

**Issue by michaldybczak** [flavioislima/HeroicGamesLauncher#74]
I added some free Battlefront game to Epic account, but it doesn't show in Heroic. It's just black. Refreshing doesn't help.
I installed Epic game store on Lutris, just to check if the game is there and indeed, I can see it. So why Heroic can't?
I'm already logged in:

![Screenshot_20210119_231943](https://user-images.githubusercontent.com/10132958/105099963-d5a27280-5aac-11eb-828c-f0408d900476.jpeg)

**Comment by GrooveStomp** [comment]
I found this article that potentially explains what is happening: https://www.toptensoftware.com/blog/running-ea-origin-games-under-linux-via-steam-and-proton/

I haven't gone through this yet myself; but tldr; apparently Origin needs to be installed for EA Origin games to sync properly.

**Comment by GrooveStomp** [comment]
Uh, this is the one I meant; although that other thread is also related:

https://www.reddit.com/r/wine_gaming/comments/kx26y7/playing_star_wars_battlefront_2_epic_games_edition/gjbuq4r/

**Comment by Linux4Good** [comment]
Look at #48

**Comment by flavioislima** [comment]
Yeah, this is a know issue and was discussed before. Epic doesn't have a manifest for it since the game is downloaded on Origin, so it is impossible for Heroic or Legendary to deal with it.

**Comment by michaldybczak** [comment]
Thanks for the explanation.
