### ISSUE TITLE
Production build from source not possible with current "npm run dist"

### ISSUE THREAD

**Issue by wiryfuture** [flavioislima/HeroicGamesLauncher#80]
If you try to build a production optimised build from source using `npm run dist`, as is recommended on the GH page, compilation doesn't successfully complete fully because something is expecting a GH workflow_token (what I can only assume is for automatic publishing to repositories?), rather irritating when I want to build from source to have the latest modifications for normal use when not actively working on code 😅

![image](https://user-images.githubusercontent.com/50517631/105214780-5a8e9a00-5b48-11eb-869f-f3513559c81a.png)

Also, while I'm talking about building for prod, maybe we could have an optional argument to only build for one platform (not really necessary but could save some time if you weren't compiling for a release).

**Comment by flavioislima** [comment]
Weird because I can build locally, but anyway, I'm removing this and will keep it only on GH. And yes, can be good to have other scripts like `build-deb`, `build-rpm`, etc.

**Comment by flavioislima** [comment]
I'll close since this was fixed on latests commits.
