### ISSUE TITLE
ARK Editor | Image not found

### ISSUE THREAD

**Issue by Razuuu** [flavioislima/HeroicGamesLauncher#81]
![Bildschirmfoto vom 2021-01-20 19-27-30](https://user-images.githubusercontent.com/40471551/105218591-a3991b00-5b55-11eb-97ec-2a1227b36475.png)
Hello,

Already with the last stable version I noticed that the ARK Editor couldn't find the image.

With best regards
Razuuu

**Comment by wiryfuture** [comment]
@Razuuu would you happen to know what if that ark logo graphic is part of the _image not found_ background? 
If it is, I'm unsure if there's much that can be done if the image source is providing this image.

**Comment by flavioislima** [comment]
So, how can I say that?
For some reason we are getting the logo but not the art. On the metadata that legendary gets from epic, we get the url for the images for the games and sometimes the dlc. When no image is found, I use this fallback one. 

So, there is nothing to do in this case since we are not getting anything for the image, that is called DieselGameboxtall on the metadata file. Even if I add another thing as the image, it would not look like a proper game cover.

**Comment by wiryfuture** [comment]
This maybe be an issue with the fact that the editor counts as a different "version" of the game, it could be worth checking out if any other games that have multiple versions have a similar issue.

**Comment by lucifertdark** [comment]
This is what stopped a previous version of Heroic from loading any of the games in collections. I'd rather have this than not be able to see any of my games.

**Comment by flavioislima** [comment]
> This is what stopped a previous version of Heroic from loading any of the games in collections. I'd rather have this than not be able to see any of my games.

Exactly, I'm still understanding how Epic metadata works and at first I thought that every game/dlc had their own image, but they didn't. So it was breaking the app when trying to use and image that didn't existed. So I added a fallback. 

@Razuuu i can see that even on Epic Store this Editor does not have a cover, only the logo. So I think everything is allright. Maybe I should just replace this fallback image with a black background.
Here is the link for it:
https://www.epicgames.com/store/en-US/browse?pageSize=30&q=ark%20editor&sortBy=relevance&sortDir=DESC

**Comment by StefanLobbenmeier** [comment]
There is also no image for "Twinmotion" (although I dont really care about that one)

![image](https://user-images.githubusercontent.com/36509607/105606743-73db5480-5d9b-11eb-8ac2-8a08e5c1248f.png)

**Comment by StefanLobbenmeier** [comment]
> On the metadata that legendary gets from epic, we get the url for the images for the games and sometimes the dlc. 

Which command is that? Then I can share the data

**Comment by StefanLobbenmeier** [comment]
Nevermind, [found it ](https://github.com/flavioislima/HeroicGamesLauncher/blob/2409837b11cb4acbb482e9148097c524b70bc3f8/electron/main.ts#L333)

And looking at my TwinMotion metatadata I saw that the attribute keyImages is an empty list:
```
    "keyImages": [],
```

**Comment by flavioislima** [comment]
> Nevermind, [found it ](https://github.com/flavioislima/HeroicGamesLauncher/blob/2409837b11cb4acbb482e9148097c524b70bc3f8/electron/main.ts#L333)
> 
> And looking at my TwinMotion metatadata I saw that the attribute keyImages is an empty list:
> 
> ```
>     "keyImages": [],
> ```

Yeah, that's why you got the fallback 'image not found'. Unfortunately will be like this for some games and there is not much we can do for now.

**Comment by flavioislima** [comment]
I'll close this one since there is not much to do.
