### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by wiryfuture** [flavioislima/HeroicGamesLauncher#84]
I know this is rather pointless right now as this is a linux project, and I personally use linux myself 😄 ...
but theoretically we could provide a windows build as Legendary has windows support and afaik electron and react are native for windows too.

Any room for discussion or no?

**Comment by flavioislima** [comment]
It should be easy to port. Just need to change the legendary binary and remove the wine part. For now I don't have windows on my computer but if you want to try, be my guest.

I also know that we can build the windows version on Linux so it should be possible to create a github action for that as well.

**Comment by wiryfuture** [comment]
I'll take a look tomorrow and see if I can get it running. 
I don't know too much about automation of building but I'm pretty sure it's possible to set up the build file to automatically remove wine components and provide a different Legendary binary.

**Comment by gonrhcp** [comment]
This would be really awesome since HGL looks and feels way better than other legendary clients!

**Comment by wiryfuture** [comment]
I've been trying to get it working with windows today and I think I'm nearly there, but the codebase looks a bit messy. It's a shame that Legendary doesn't have osx support because I could have done it for that as well in one fell swoop.

**Comment by flavioislima** [comment]
> I've been trying to get it working with windows today and I think I'm nearly there, but the codebase looks a bit messy. It's a shame that Legendary doesn't have osx support because I could have done it for that as well in one fell swoop.

i dont know how are you doing, but would be good to have two main files, one for Linux and other for Window, that would make things easier. And also keep the things that both use on the utils file.

**Comment by Ridhubharan** [comment]
I personally think it should be a "Linux Exclusive". It's just a suggestion!

**Comment by wiryfuture** [comment]
> I personally think it should be a "Linux Exclusive". It's just a suggestion!

Imo if it's meant to be a GUI for a replacement of the epic games launcher, I think it's only good to do better than the epic games launcher itself and try support as much as possible.

**Comment by wiryfuture** [comment]
I've got a solid idea on how to structure this now but I've had to restart because of it 😹
No need to worry though because my biggest hurdle is just importing the initial functions. I was hoping you could do something along the lines of `import {x, y, z} from platformvar`, but you can only import with String literals, so the next best thing I can think of is to have some sort of wrapper that has all the functions imported and decides which to use depending on platform?
I don't like that solution too much though because it's adding runtime bloat.

**Comment by wiryfuture** [comment]
I'm going to close this issue for now, as I think it's impractical to do this while the codebase is changing so much. I'll have a look at this later when most things have been implemented and the packages etc won't be changing.
