### ISSUE TITLE
Proton GE

### ISSUE THREAD

**Issue by ALipAkrohk** [flavioislima/HeroicGamesLauncher#85]
Hello, my question is do you support proton ?!
I use [ProtonGE](https://github.com/GloriousEggroll/proton-ge-custom) but I can not use it in Heroic.
What is the procedure like?
![image](https://user-images.githubusercontent.com/27810360/105252748-49b74600-5b93-11eb-9dc4-5546d10d7032.png)

**Comment by flavioislima** [comment]
This is a warning to not mess up with your default prefix. But I removed this on latest version. Upgrade to 1.1.2.

**Comment by ALipAkrohk** [comment]
> This is a warning to not mess up with your default prefix. But I removed this on latest version. Upgrade to 1.1.2.

tank :+1:
