### ISSUE TITLE
The new dependency for version 1.1.2

### ISSUE THREAD

**Issue by Ahmed-E-86** [flavioislima/HeroicGamesLauncher#86]
After adding wine as a dependency at version 1.1.2, it requires removing winehq-staging, or winehq-devel if it is installed.
![Screenshot_20210121_013722](https://user-images.githubusercontent.com/29783425/105254290-e07f0500-5b89-11eb-92c4-dc363e0fcc50.png)

**Comment by wiryfuture** [comment]
This should be an easy fix; (may not be quite exact syntax, but) change the `build-depends` from `wine` to `wine-* | wine` so that any wine build can be used

**Comment by bayazidbh** [comment]
Ah, I suppose this is the issue reporting for wine and winetricks dependencies errors? I use Fedora 33, and here is my log for reference:

```
$ sudo rpm -U heroic-1.1.2.x86_64.rpm
> error: Failed dependencies:
> 	wine is needed by heroic-1.1.2-1.x86_64
> 	winetricks is needed by heroic-1.1.2-1.x86_64
$ whereis wine
> wine: /usr/bin/wine /opt/wine-staging/bin/wine /opt/cxoffice/bin/wine /usr/share/man/man1/wine.1.gz
$ whereis winetricks
> winetricks: /usr/local/bin/winetricks
$ dnf list --installed wine*
> Installed Packages
> wine-staging-common.i686                   1:6.0.0-1.1                   @WineHQ
> wine-staging64.x86_64                      1:6.0.0-1.1                   @WineHQ
> winehq-staging.x86_64                      1:6.0.0-1.1                   @WineHQ
```

Note that I didn't install winetricks as a package on my setup as on Fedora 33 at least, installing it as a package depends on wine-common provider which conflicted with wine-staging.

Should the two really remain as a dependency when installing though? I'm not programmer, but I think it might just be better that it tries to detect if the command `wine` and `winetricks` would work or not, and then offers to install them if it doesn't find them working. There are a whole load of different wine packages after all, not to mention custom builds. Just my two cents.

**Comment by flavioislima** [comment]
I'll remove these dependencies then and try to put them as optional.
