### ISSUE TITLE
Settings listing game as wine version.

### ISSUE THREAD

**Issue by lucifertdark** [flavioislima/HeroicGamesLauncher#87]
I've just installed 1.1.2 & settings is listing Aegis of Earth Protonovus Assault as a version of Wine/Proton, it's doubly odd as I don't even have that game installed at the moment.

![settings](https://user-images.githubusercontent.com/43232878/105334475-d3d0d000-5bce-11eb-8f72-7db89219e3f2.jpeg)

Ubuntu 20.04.1, all drivers up to date, Steam is also the latest available Beta.

**Comment by flavioislima** [comment]
This is due to my stupid search algorithm that is looking for everything that contains "proton" on the name. I'll put a fix for it on the next release.

**Comment by lucifertdark** [comment]
I didn't notice the Proton in the name even though I typed it. :) I'll close this as you're already aware of it.
