### ISSUE TITLE
Delete old SID/Login API code

### ISSUE THREAD

**Issue by Giovix92** [flavioislima/HeroicGamesLauncher#9]
Hello, I've mistakenly logged in with an older account, and can't really find any file inside my home that points to the used SID. Where is it located? Thank you in advance!

**Comment by flavioislima** [comment]
HI! I'll add an option to logout soon. For now you can delete the .config/legendary folder.

**Comment by Giovix92** [comment]
Thank you! It worked!

**Comment by flavioislima** [comment]
> Thank you! It worked! I'd suggest you to add it in the Readme :)

I added a logout option now on 0.4.0 so this should fix the issue for good.
Thanks, man!

**Comment by Giovix92** [comment]
Thank you for working hard on this!
