### ISSUE TITLE
Support proton-ge-custom on Arch

### ISSUE THREAD

**Issue by Ryan659** [flavioislima/HeroicGamesLauncher#91]
On AUR, `proton-ge-custom` and `proton-ge-custom-bin` install to `/usr/share/steam/compatibilitytools.d/proton-ge-custom` but Heroic doesn't see this. Could you please support this path?

**Comment by flavioislima** [comment]
Ok, I'll add the path on next release!

**Comment by flavioislima** [comment]
Added and tested the change on the Main branch.
Since I use Manjaro that is arch based, was easy to try.
Next release will contain the fix. And probably a way to add custom folders for Wine and Proton as well.
