### ISSUE TITLE
Launcher does nothing after deleting an imported game's directory

### ISSUE THREAD

**Issue by Serial-ATA** [flavioislima/HeroicGamesLauncher#93]
I had a game installed already and imported it to try out the launcher. Since it ended up working I moved the folder to the default path I set in the launcher. I don't see a way to change the game's directory in the launcher and clicking uninstall does nothing.

[Sugar-lastPlay.log](https://github.com/flavioislima/HeroicGamesLauncher/files/5856806/Sugar-lastPlay.log)
The launcher still tries to use this path even though it no longer exists. Am I missing a setting somewhere?

**Comment by flavioislima** [comment]
Weird, should be possible to uninstall and import again.
can you run heroic from terminal, click on the uninstall button and see the message that you're getting?

**Comment by Serial-ATA** [comment]
Not really sure what happened, but after trying uninstall a few times it just ended up working. Now it works first try every time. Sorry I couldn't get any logs.

**Comment by flavioislima** [comment]
Added a message now when having errors uninstalling a game.
