### ISSUE TITLE
Download size is wrong when downloading some games (Hob), but not for all (Superhot)

### ISSUE THREAD

**Issue by StefanLobbenmeier** [flavioislima/HeroicGamesLauncher#95]
I just attempted to download the game "Hob" using Heroic. When I saw that it was 15GB big I cancelled the download. 
When I later looked at the steam page I found that it is only supposed to require 5 GB of space.
I then downloaded it through legendary and it reported that it would use 2GB.

Sorry the rest is a bit of a ramble while I tried to reason with what I was seeing. Lots of data though so maybe you can find out what is happening :smiley: 

But what I noticed during the legendary login is that the Progress indicator seems to be the one that is used to determine the size (14804). I am actually not sure what this unit describes, but maybe it is bit instead of byte?
```
[DLManager] INFO: = Progress: 96.20% (14241/14804), Running for 00:04:49, ETA: 00:00:11
[DLManager] INFO:  - Downloaded: 1540.52 MiB, Written: 1931.22 MiB
[DLManager] INFO:  - Cache usage: 27.0 MiB, active tasks: 24
[DLManager] INFO:  + Download   - 6.92 MiB/s (raw) / 6.99 MiB/s (decompressed)
[DLManager] INFO:  + Disk       - 4.00 MiB/s (write) / 0.00 MiB/s (read)
```

To get screenshots I now tried to reproduce with a new game (Superhot):
Screenshot from Heroic:
![image](https://user-images.githubusercontent.com/36509607/105530824-a710db80-5ce8-11eb-8c2e-2ba558aee5b4.png)

But for that one it is correct:
```
[DLM] DEBUG: Biggest chunk size: 1048576 bytes (== 1 MiB? True)
[DLM] DEBUG: Creating manifest comparison...
[DLM] INFO: Found previously interrupted download. Download will be resumed if possible.
[DLM] INFO: Skipping 157 files based on resume data.
[DLM] DEBUG: 292 added files
[DLM] DEBUG: 157 unchanged files
[DLM] DEBUG: Creating filetasks and chunktasks...
[DLM] DEBUG:  * New maximum cache size: 3.00 MiB
[DLM] DEBUG: Final cache size requirement: 3.0 MiB.
[cli] INFO: Install size: 4156.85 MiB
[cli] INFO: Download size: 1129.36 MiB (Compression savings: 67.8%)
[cli] INFO: Reusable size: 0.00 MiB (chunks) / 576.09 MiB (unchanged / skipped)
[cli] INFO: Downloads are resumable, you can interrupt the download with CTRL-C and resume it using the same command later on.
Do you wish to install "SUPERHOT"? [Y/n]: 
```

Hmm so now I uninstalled Hob again so I can verify in Heroic:
![image](https://user-images.githubusercontent.com/36509607/105531118-21416000-5ce9-11eb-8af6-de20144baaea.png)

I thought maybe the chunk size is different but it is also 1MB in legendary:
```
[DLM] DEBUG: Biggest chunk size: 1048576 bytes (== 1 MiB? True)
[DLM] DEBUG: Creating manifest comparison...
[DLM] INFO: Found previously interrupted download. Download will be resumed if possible.
[DLM] INFO: Skipping 33 files based on resume data.
[DLM] DEBUG: 12294 added files
[DLM] DEBUG: 33 unchanged files
[DLM] DEBUG: Creating filetasks and chunktasks...
[DLM] DEBUG:  * New maximum cache size: 1.00 MiB
[DLM] DEBUG: Final cache size requirement: 1.0 MiB.
[cli] INFO: Install size: 2482.29 MiB
[cli] INFO: Download size: 1908.46 MiB (Compression savings: 17.1%)
[cli] INFO: Reusable size: 0.00 MiB (chunks) / 181.13 MiB (unchanged / skipped)
[cli] INFO: Downloads are resumable, you can interrupt the download with CTRL-C and resume it using the same command later on.
Do you wish to install "Hob"? [Y/n]: 

```

**Comment by flavioislima** [comment]
I noticed this as well this week when was downloading a few game.
For now, I'm using this line to show the progress:
`[DLManager] INFO: = Progress: 96.20% (14241/14804), Running for 00:04:49, ETA: 00:00:11`
Then I use AWK to get the % and the content inside the parenthesis.

When implemented, I thought it was the size in MB, but now I think it isn't so, I don't know, I'll try to get this info from the legendary devs or change the MB for, I don't know, 'parts', 'pieces', something like this. Or completely remove it.

**Comment by StefanLobbenmeier** [comment]
Probably related, but for Superhot the install size is wrong:
![image](https://user-images.githubusercontent.com/36509607/105606627-cf591280-5d9a-11eb-85ea-fedb23d79edd.png)

```
➜  ~ legendary list-installed

Installed games:
 * SUPERHOT (App name: Dory | Version: 1.0.17a_002 | 4.06 GiB)
```

**Comment by flavioislima** [comment]
> Probably related, but for Superhot the install size is wrong:
> ![image](https://user-images.githubusercontent.com/36509607/105606627-cf591280-5d9a-11eb-85ea-fedb23d79edd.png)
> 
> ```
> ➜  ~ legendary list-installed
> 
> Installed games:
>  * SUPERHOT (App name: Dory | Version: 1.0.17a_002 | 4.06 GiB)
> ```

Hmm, that's even more weird because for the installed size I'm getting the info from the legendary installed.json file.
I have superhot, will install it and check why is different.

**Comment by flavioislima** [comment]
@StefanLobbenmeier I did the comparissons bellow and it looks like it is legendary that is calculating the GB wrong. I'll talk with them to check how they are calculating the size. Because Heroic is showing the downloaded size, on disk, and maybe legendary is showing the download size. I'm not sure, but take a look:

![tyranny-size](https://user-images.githubusercontent.com/26871415/105630037-d9384f80-5e46-11eb-916f-372032ecc382.png)
![control-size](https://user-images.githubusercontent.com/26871415/105630038-d9d0e600-5e46-11eb-9854-850fbf35240a.png)
