### ISSUE TITLE
Proton Issue

### ISSUE THREAD

**Issue by paulopaim** [flavioislima/HeroicGamesLauncher#96]
Hello!
I was receiving the following error when I tried to start the games using proton:

- FileNotFoundError: [Errno 2] No such file or directory: '~/.wine/pfx.lock'

So I create the folder:

- '~/.wine/'

And then the game starts normally.

Another thing, if I don't put the following attribute in the: 'Default WinePrefix' option:

- ~/.wine

The game won't start as well, it needs this attribute to run, even if I select proton.
![Screenshot from 2021-01-22 16-25-13](https://user-images.githubusercontent.com/15007933/105536004-715ef900-5cce-11eb-9eb2-71a9f6cffd33.png)

**Comment by flavioislima** [comment]
That's because the prefix folder needs to exist for Heroic to launch the game.
Maybe I should put a check before launching the game. I assume that everyone uses Wine and Steam but I'm starting to see that this is not the case.

**Comment by flavioislima** [comment]
On my current branch I added a check if the prefix exists when using proton and if not the folder is created.
The thing is that when using wine, if the folder does not exists, it will create it. But Proton, for some reason, doesnt, it expects that the folder already exists.
