### ISSUE TITLE
Returning to library during update stops it

### ISSUE THREAD

**Issue by Serial-ATA** [flavioislima/HeroicGamesLauncher#98]
Updating works fine, but when you go to the library it stops, and when you go back to the game it tries to launch rather than continuing the update. The only way for it to continue the update is to uninstall then reimport.
[log.txt](https://github.com/flavioislima/HeroicGamesLauncher/files/5858602/log.txt)
The log has comments with what I'm doing.

Should note this doesn't happen with downloads, just updates.

**Comment by flavioislima** [comment]
Weird. I'll check.

**Comment by flavioislima** [comment]
I think it keeps running in the background but on the frontend the state of the update is lost.

**Comment by Serial-ATA** [comment]
When I went back to the game and tried to play it it would launch, but nothing would happen and I'd have to kill it. I assumed it just forgot about the update and tried running anyway.

**Comment by flavioislima** [comment]
Fixed on my current branch. Now heroic will treat an updating game as a new installation and the game will be shown as installing on the library.

**Comment by flavioislima** [comment]
Fixed on latest release.
