### ISSUE TITLE
Desktop file has each character on its own numbered line

### ISSUE THREAD

**Issue by Serial-ATA** [flavioislima/HeroicGamesLauncher#99]
I've installed heroic from the aur (heroic-games-launcher-bin) not sure if that makes a difference. The desktop file (/usr/share/applications/heroic.desktop) has everything it should, but every character is on its own line. Everything's right at the bottom.

<details>
<summary>heroic.desktop</summary>
[Desktop Entry]</br>
0=N</br>
1=a</br>
2=m</br>
3=e</br>
4==</br>
5=H</br>
6=e</br>
7=r</br>
8=o</br>
9=i</br>
10=c</br>
11= </br>
12=E</br>
13=x</br>
14=e</br>
15=c</br>
16==</br>
17=h</br>
18=e</br>
19=r</br>
20=o</br>
21=i</br>
22=c</br>
23= </br>
24=I</br>
25=c</br>
26=o</br>
27=n</br>
28==</br>
29=h</br>
30=e</br>
31=r</br>
32=o</br>
33=i</br>
34=c</br>
35= </br>
36=T</br>
37=y</br>
38=p</br>
39=e</br>
40==</br>
41=A</br>
42=p</br>
43=p</br>
44=l</br>
45=i</br>
46=c</br>
47=a</br>
48=t</br>
49=i</br>
50=o</br>
51=n</br>
52= </br>
53=C</br>
54=a</br>
55=t</br>
56=e</br>
57=g</br>
58=o</br>
59=r</br>
60=i</br>
61=e</br>
62=s</br>
63==</br>
64=g</br>
65=a</br>
66=m</br>
67=e</br>
68=s</br>
Name=heroic</br>
Exec=/opt/heroic/heroic %U</br>
Terminal=false</br>
Type=Application</br>
Icon=heroic</br>
StartupWMClass=heroic</br>
Comment=Native Epic Games Launcher alternative for Linux based on Legendary</br>
Categories=Game;
</details>

Not a huge deal, just odd.

**Comment by flavioislima** [comment]
That's funny because it's true. Electron-builder is doing something weird.

**Comment by flavioislima** [comment]
Fixed on latest version
